#+TITLE: mac-dev-setup-notes
#+DATE: <2019-01-29 Tue>
#+AUTHOR: Jacob Motley
* Mac OSX Version
Mojave: 10.14.3 (18D42)
* Python3 Version
Python 3.7.2
* Steps to getting pddesk to development setup on OSX Mojave
** Installed Qt5 / QtCreator
** Upgraded pip
pip3 install --upgrade pip
** (pip) Installed wheel
pip3 install wheel
** (pip) started installing requirements (all but qt-related)
pip3 install requests pandas numpy reportlab
** (brew) installed pyqt5 - (brew is an osx package manager)
link - https://brew.sh/
brew update (update brew first)
brew install pyqt5
*** saved some brew output for later
We agreed to the Qt open source license for you.
If this is unacceptable you should uninstall.

qt is keg-only, which means it was not symlinked into /usr/local,
because Qt 5 has CMake issues when linked.

If you need to have qt first in your PATH run:
  echo 'set -g fish_user_paths "/usr/local/opt/qt/bin" $fish_user_paths' >> ~/.config/fish/config.fish

For compilers to find qt you may need to set:
  set -gx LDFLAGS "-L/usr/local/opt/qt/lib"
  set -gx CPPFLAGS "-I/usr/local/opt/qt/include"

==> sip
The sip-dir for Python is /usr/local/share/sip.
** At this point I started having to use python3 -m pip because brew installed another python3
** (pip) installed PyQt5
python3 -m pip install PyQt5
** (pip) installed qdarkstyle
python3 -m pip install qdarkstyle
** Then comes the nugget
** (pip) attempt 1. install popplerqt5 from pip3 (FAILED)
*** output
  Downloading https://files.pythonhosted.org/packages/af/e7/aa451d4ca0910472c4442d8aa6ef44300852926d85ad033b029a22157027/python-poppler-qt5-0.24.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/mf/mdf61kbx5c1_6d9l1p342xfh0000gn/T/pip-install-bre47cec/python-poppler-qt5/setup.py", line 42, in <module>
        import sipdistutils
    ModuleNotFoundError: No module named 'sipdistutils'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/mf/mdf61kbx5c1_6d9l1p342xfh0000gn/T/pip-install-bre47cec/python-poppler-qt5/
** (pip) fix time... install pip from pip3 (part 1)
python3 -m pip install sip
** (pip) attempt 2. install popplerqt5 from pip3 (FAILED)
*** output
Collecting python-poppler-qt5
  Using cached https://files.pythonhosted.org/packages/af/e7/aa451d4ca0910472c4442d8aa6ef44300852926d85ad033b029a22157027/python-poppler-qt5-0.24.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/mf/mdf61kbx5c1_6d9l1p342xfh0000gn/T/pip-install-e5rbr2zw/python-poppler-qt5/setup.py", line 42, in <module>
        import sipdistutils
    ModuleNotFoundError: No module named 'sipdistutils'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/mf/mdf61kbx5c1_6d9l1p342xfh0000gn/T/pip-install-e5rbr2zw/python-poppler-qt5/
** (sipdistutils) fix time... put sipdistutils.py directly into the site-packages folder
*** link to source
https://www.riverbankcomputing.com/hg/sip/file/14685a6e736e/sipdistutils.py
** (pip) attempt 3. install popplerqt5 from pip3 (FAILED)
*** how do I find the site-packages folder?
python3 -m site
**** output
...stuff
'/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages',
...stuff
*** copy sipdistutils
cp sipdistutils.py /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/
*** output
Collecting python-poppler-qt5
  Using cached https://files.pythonhosted.org/packages/af/e7/aa451d4ca0910472c4442d8aa6ef44300852926d85ad033b029a22157027/python-poppler-qt5-0.24.2.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/python_poppler_qt5.egg-info
    writing pip-egg-info/python_poppler_qt5.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/python_poppler_qt5.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/python_poppler_qt5.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/python_poppler_qt5.egg-info/SOURCES.txt'
    Failed to determine Qt version ([Errno 2] No such file or directory: 'qmake': 'qmake').
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/mf/mdf61kbx5c1_6d9l1p342xfh0000gn/T/pip-install-fwit88ly/python-poppler-qt5/
** (qt) go back to brew output from before (FAILED)
*** try this line (nope)?
echo 'set -g fish_user_paths "/usr/local/opt/qt/bin" $fish_user_paths' >> ~/.config/fish/config.fish
*** try my own command (set is used with fish) (partial success)
set PATH /usr/local/opt/qt/bin:$PATH; and export PATH
**** output
    ModuleNotFoundError: No module named 'sipconfig'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/mf/mdf61kbx5c1_6d9l1p342xfh0000gn/T/pip-install-vge9_68j/python-poppler-qt5/
*** try getting sip source to get sipconfig file (not there, try siputils.py?) (FAILED)
**** link
https://www.riverbankcomputing.com/software/sip/download

**** cp to site-packages
cp siputils.py /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/
**** still the same error (sipconfig)
** (sipconfig) alright just bear with me (FAILED)
*** get the sip source code
http://pyqt.sourceforge.net/Docs/sip4/installation.html
*** run python configure.py in source code dir
*** this generates sipconfig.py
**** copy it to site-packages
cp sipconfig.py /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/
**** say dammit again! (FAILED)
***** output
    unable to execute '/Library/Frameworks/Python.framework/Versions/3.7/bin/sip': No such file or directory
    error: command '/Library/Frameworks/Python.framework/Versions/3.7/bin/sip' failed with exit status 1
**** 'which sip' and find location
/usr/local/bin/sip
**** copy sip to /Library/Frameworks/Python.framework/Versions/3.7/bin/sip
cp /usr/local/bin/sip /Library/Frameworks/Python.framework/Versions/3.7/bin/sip
**** failed again
error: command '/Library/Frameworks/Python.framework/Versions/3.7/bin/sip' failed with exit status 1
** DONE try the dev release from riverbankcomputing (***SUCCESS***)
*** uninstall pyqt5 and sip from brew
**** uninstall pyqt5 and sip from brew
**** delete sip* from site-packages
**** output
    sip: Deprecation warning: poppler-qt5.sip:1: %Module version numbers are deprecated and ignored
    sip: Unable to find file "QtCore/QtCoremod.sip"
    error: command '/Library/Frameworks/Python.framework/Versions/3.7/bin/sip' failed with exit status 1
*** uninstall pyqt5 and sip from pip
*** install sip from source
**** link
https://www.riverbankcomputing.com/software/sip/download
*** install PyQt5 from source
**** link
https://www.riverbankcomputing.com/software/pyqt/download
*** try installing popplerqt5 from macports (FAILED)
**** link
https://www.macports.org/ports.php?by=library&substr=poppler-qt5
**** add port to path in fish
set PATH /opt/local/bin:/opt/local/sbin:$PATH; and export PATH
**** requires enabling root user on mac
*** install popplerqt5 from source (SUCCESS!)
**** bug fix in repo
file types.sip
@ line 30
change: if (obj == NULL || PyList_SET_ITEM (l, i, obj) < 0)
    to: if (obj == (void *)NULL || !(PyList_SET_ITEM (l, i, obj)))
**** install with
CFLAGS=-std=c++11 QT_SELECT=5 python3 setup.py install
