# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/collBookUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(940, 666)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 3, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formView = formView(self.centralwidget)
        self.formView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formView.sizePolicy().hasHeightForWidth())
        self.formView.setSizePolicy(sizePolicy)
        self.formView.setMinimumSize(QtCore.QSize(0, 0))
        self.formView.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.formView.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.formView.setStyleSheet("font: 12pt \"Cantarell\";")
        self.formView.setObjectName("formView")
        self.StackedWidgetPage1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StackedWidgetPage1.sizePolicy().hasHeightForWidth())
        self.StackedWidgetPage1.setSizePolicy(sizePolicy)
        self.StackedWidgetPage1.setObjectName("StackedWidgetPage1")
        self.gridLayout = QtWidgets.QGridLayout(self.StackedWidgetPage1)
        self.gridLayout.setContentsMargins(0, 3, 0, 3)
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_newSite = QtWidgets.QPushButton(self.StackedWidgetPage1)
        self.pushButton_newSite.setObjectName("pushButton_newSite")
        self.horizontalLayout_13.addWidget(self.pushButton_newSite)
        self.gridLayout.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(9)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.gridGroupBox = QtWidgets.QGroupBox(self.StackedWidgetPage1)
        self.gridGroupBox.setCheckable(False)
        self.gridGroupBox.setChecked(False)
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridGroupBox)
        self.gridLayout_6.setContentsMargins(0, 3, -1, 3)
        self.gridLayout_6.setVerticalSpacing(3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.plainTextEdit_fieldNotes = QtWidgets.QPlainTextEdit(self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_fieldNotes.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_fieldNotes.setSizePolicy(sizePolicy)
        self.plainTextEdit_fieldNotes.setMinimumSize(QtCore.QSize(0, 45))
        self.plainTextEdit_fieldNotes.setMaximumSize(QtCore.QSize(16777215, 55))
        self.plainTextEdit_fieldNotes.setSizeIncrement(QtCore.QSize(0, 0))
        self.plainTextEdit_fieldNotes.setBaseSize(QtCore.QSize(0, 0))
        self.plainTextEdit_fieldNotes.setObjectName("plainTextEdit_fieldNotes")
        self.gridLayout_6.addWidget(self.plainTextEdit_fieldNotes, 1, 1, 1, 1)
        self.label_samplingEffort = QtWidgets.QLabel(self.gridGroupBox)
        self.label_samplingEffort.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_samplingEffort.setObjectName("label_samplingEffort")
        self.gridLayout_6.addWidget(self.label_samplingEffort, 3, 0, 1, 1)
        self.label_eventRemarks = QtWidgets.QLabel(self.gridGroupBox)
        self.label_eventRemarks.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_eventRemarks.setObjectName("label_eventRemarks")
        self.gridLayout_6.addWidget(self.label_eventRemarks, 2, 0, 1, 1)
        self.label_fieldNotes = QtWidgets.QLabel(self.gridGroupBox)
        self.label_fieldNotes.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_fieldNotes.setObjectName("label_fieldNotes")
        self.gridLayout_6.addWidget(self.label_fieldNotes, 1, 0, 1, 1)
        self.lineEdit_samplingEffort = QtWidgets.QLineEdit(self.gridGroupBox)
        self.lineEdit_samplingEffort.setObjectName("lineEdit_samplingEffort")
        self.gridLayout_6.addWidget(self.lineEdit_samplingEffort, 3, 1, 1, 1)
        self.lineEdit_eventRemarks = QtWidgets.QLineEdit(self.gridGroupBox)
        self.lineEdit_eventRemarks.setObjectName("lineEdit_eventRemarks")
        self.gridLayout_6.addWidget(self.lineEdit_eventRemarks, 2, 1, 1, 1)
        self.label_labelProject = QtWidgets.QLabel(self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_labelProject.sizePolicy().hasHeightForWidth())
        self.label_labelProject.setSizePolicy(sizePolicy)
        self.label_labelProject.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_labelProject.setObjectName("label_labelProject")
        self.gridLayout_6.addWidget(self.label_labelProject, 0, 0, 1, 1)
        self.plainTextEdit_labelProject = QtWidgets.QPlainTextEdit(self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_labelProject.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_labelProject.setSizePolicy(sizePolicy)
        self.plainTextEdit_labelProject.setMinimumSize(QtCore.QSize(0, 45))
        self.plainTextEdit_labelProject.setMaximumSize(QtCore.QSize(16777215, 55))
        self.plainTextEdit_labelProject.setObjectName("plainTextEdit_labelProject")
        self.gridLayout_6.addWidget(self.plainTextEdit_labelProject, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.gridGroupBox)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(0, 3, -1, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 3, -1, -1)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.radioButton_applyAllRecords = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_applyAllRecords.setChecked(True)
        self.radioButton_applyAllRecords.setObjectName("radioButton_applyAllRecords")
        self.verticalLayout_6.addWidget(self.radioButton_applyAllRecords)
        self.radioButton_applySelectSites = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_applySelectSites.setObjectName("radioButton_applySelectSites")
        self.verticalLayout_6.addWidget(self.radioButton_applySelectSites)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalFrame_2 = QtWidgets.QFrame(self.frame_3)
        self.verticalFrame_2.setEnabled(False)
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_8.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_8.setSpacing(3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.treeWidget_sitesToApply = QtWidgets.QTreeWidget(self.verticalFrame_2)
        self.treeWidget_sitesToApply.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_sitesToApply.sizePolicy().hasHeightForWidth())
        self.treeWidget_sitesToApply.setSizePolicy(sizePolicy)
        self.treeWidget_sitesToApply.setMinimumSize(QtCore.QSize(0, 0))
        self.treeWidget_sitesToApply.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.treeWidget_sitesToApply.setFont(font)
        self.treeWidget_sitesToApply.setHeaderHidden(True)
        self.treeWidget_sitesToApply.setObjectName("treeWidget_sitesToApply")
        self.treeWidget_sitesToApply.headerItem().setTextAlignment(0, QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_sitesToApply)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        self.verticalLayout_8.addWidget(self.treeWidget_sitesToApply)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.toolButton_sitesToApply_SelectNone = QtWidgets.QToolButton(self.verticalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_sitesToApply_SelectNone.sizePolicy().hasHeightForWidth())
        self.toolButton_sitesToApply_SelectNone.setSizePolicy(sizePolicy)
        self.toolButton_sitesToApply_SelectNone.setObjectName("toolButton_sitesToApply_SelectNone")
        self.horizontalLayout_15.addWidget(self.toolButton_sitesToApply_SelectNone)
        self.toolButton_sitesToApply_SelectAll = QtWidgets.QToolButton(self.verticalFrame_2)
        self.toolButton_sitesToApply_SelectAll.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_sitesToApply_SelectAll.sizePolicy().hasHeightForWidth())
        self.toolButton_sitesToApply_SelectAll.setSizePolicy(sizePolicy)
        self.toolButton_sitesToApply_SelectAll.setObjectName("toolButton_sitesToApply_SelectAll")
        self.horizontalLayout_15.addWidget(self.toolButton_sitesToApply_SelectAll)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.verticalLayout_2.addWidget(self.verticalFrame_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.gridLayout_6.addWidget(self.frame_3, 0, 2, 4, 1)
        self.gridLayout_6.setColumnStretch(0, 1)
        self.gridLayout_6.setColumnStretch(1, 5)
        self.gridLayout_6.setColumnStretch(2, 2)
        self.horizontalLayout_16.addWidget(self.gridGroupBox)
        self.gridLayout.addLayout(self.horizontalLayout_16, 2, 0, 1, 2)
        self.groupBox_newSite_defaults = QtWidgets.QGroupBox(self.StackedWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_newSite_defaults.sizePolicy().hasHeightForWidth())
        self.groupBox_newSite_defaults.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_newSite_defaults.setFont(font)
        self.groupBox_newSite_defaults.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_newSite_defaults.setCheckable(True)
        self.groupBox_newSite_defaults.setChecked(False)
        self.groupBox_newSite_defaults.setObjectName("groupBox_newSite_defaults")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_newSite_defaults)
        self.gridLayout_5.setContentsMargins(-1, 6, -1, 3)
        self.gridLayout_5.setVerticalSpacing(3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_default_eventDate = QtWidgets.QLabel(self.groupBox_newSite_defaults)
        self.label_default_eventDate.setObjectName("label_default_eventDate")
        self.gridLayout_5.addWidget(self.label_default_eventDate, 0, 0, 1, 1)
        self.label_default_recordedBy = QtWidgets.QLabel(self.groupBox_newSite_defaults)
        self.label_default_recordedBy.setObjectName("label_default_recordedBy")
        self.gridLayout_5.addWidget(self.label_default_recordedBy, 0, 1, 1, 1)
        self.label_default_associatedCollectors = QtWidgets.QLabel(self.groupBox_newSite_defaults)
        self.label_default_associatedCollectors.setObjectName("label_default_associatedCollectors")
        self.gridLayout_5.addWidget(self.label_default_associatedCollectors, 0, 2, 1, 1)
        self.dateEdit_default_eventDate = QtWidgets.QDateEdit(self.groupBox_newSite_defaults)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_default_eventDate.sizePolicy().hasHeightForWidth())
        self.dateEdit_default_eventDate.setSizePolicy(sizePolicy)
        self.dateEdit_default_eventDate.setWrapping(False)
        self.dateEdit_default_eventDate.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_default_eventDate.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit_default_eventDate.setAccelerated(False)
        self.dateEdit_default_eventDate.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEdit_default_eventDate.setCalendarPopup(True)
        self.dateEdit_default_eventDate.setCurrentSectionIndex(2)
        self.dateEdit_default_eventDate.setObjectName("dateEdit_default_eventDate")
        self.gridLayout_5.addWidget(self.dateEdit_default_eventDate, 1, 0, 1, 1)
        self.lineEdit_default_recordedBy = QtWidgets.QLineEdit(self.groupBox_newSite_defaults)
        self.lineEdit_default_recordedBy.setObjectName("lineEdit_default_recordedBy")
        self.gridLayout_5.addWidget(self.lineEdit_default_recordedBy, 1, 1, 1, 1)
        self.lineEdit_default_associatedCollectors = QtWidgets.QLineEdit(self.groupBox_newSite_defaults)
        self.lineEdit_default_associatedCollectors.setObjectName("lineEdit_default_associatedCollectors")
        self.gridLayout_5.addWidget(self.lineEdit_default_associatedCollectors, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_newSite_defaults, 4, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 1)
        self.formView.addWidget(self.StackedWidgetPage1)
        self.StackedWidgetPage2 = QtWidgets.QWidget()
        self.StackedWidgetPage2.setObjectName("StackedWidgetPage2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.StackedWidgetPage2)
        self.verticalLayout_3.setContentsMargins(0, 3, 0, 3)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_newSpecimen = QtWidgets.QPushButton(self.StackedWidgetPage2)
        self.pushButton_newSpecimen.setObjectName("pushButton_newSpecimen")
        self.horizontalLayout_12.addWidget(self.pushButton_newSpecimen)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.checkBox_delSite = QtWidgets.QCheckBox(self.StackedWidgetPage2)
        self.checkBox_delSite.setText("")
        self.checkBox_delSite.setObjectName("checkBox_delSite")
        self.horizontalLayout_12.addWidget(self.checkBox_delSite)
        self.pushButton_deleteSite = QtWidgets.QPushButton(self.StackedWidgetPage2)
        self.pushButton_deleteSite.setEnabled(False)
        self.pushButton_deleteSite.setObjectName("pushButton_deleteSite")
        self.horizontalLayout_12.addWidget(self.pushButton_deleteSite)
        self.verticalLayout_9.addLayout(self.horizontalLayout_12)
        self.groupGrid_event = QtWidgets.QGroupBox(self.StackedWidgetPage2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupGrid_event.sizePolicy().hasHeightForWidth())
        self.groupGrid_event.setSizePolicy(sizePolicy)
        self.groupGrid_event.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupGrid_event.setCheckable(False)
        self.groupGrid_event.setObjectName("groupGrid_event")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupGrid_event)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setContentsMargins(0, 6, -1, 0)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.dateEdit_eventDate = QtWidgets.QDateEdit(self.groupGrid_event)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_eventDate.sizePolicy().hasHeightForWidth())
        self.dateEdit_eventDate.setSizePolicy(sizePolicy)
        self.dateEdit_eventDate.setWrapping(False)
        self.dateEdit_eventDate.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_eventDate.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit_eventDate.setAccelerated(False)
        self.dateEdit_eventDate.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEdit_eventDate.setCalendarPopup(True)
        self.dateEdit_eventDate.setCurrentSectionIndex(2)
        self.dateEdit_eventDate.setObjectName("dateEdit_eventDate")
        self.gridLayout_4.addWidget(self.dateEdit_eventDate, 1, 0, 1, 1)
        self.lineEdit_recordedBy = QtWidgets.QLineEdit(self.groupGrid_event)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_recordedBy.sizePolicy().hasHeightForWidth())
        self.lineEdit_recordedBy.setSizePolicy(sizePolicy)
        self.lineEdit_recordedBy.setObjectName("lineEdit_recordedBy")
        self.gridLayout_4.addWidget(self.lineEdit_recordedBy, 1, 1, 1, 1)
        self.label_associatedCollectors = QtWidgets.QLabel(self.groupGrid_event)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_associatedCollectors.sizePolicy().hasHeightForWidth())
        self.label_associatedCollectors.setSizePolicy(sizePolicy)
        self.label_associatedCollectors.setWordWrap(False)
        self.label_associatedCollectors.setObjectName("label_associatedCollectors")
        self.gridLayout_4.addWidget(self.label_associatedCollectors, 0, 2, 1, 1)
        self.label_eventDate = QtWidgets.QLabel(self.groupGrid_event)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_eventDate.sizePolicy().hasHeightForWidth())
        self.label_eventDate.setSizePolicy(sizePolicy)
        self.label_eventDate.setWordWrap(False)
        self.label_eventDate.setObjectName("label_eventDate")
        self.gridLayout_4.addWidget(self.label_eventDate, 0, 0, 1, 1)
        self.label_recordedBy = QtWidgets.QLabel(self.groupGrid_event)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_recordedBy.sizePolicy().hasHeightForWidth())
        self.label_recordedBy.setSizePolicy(sizePolicy)
        self.label_recordedBy.setObjectName("label_recordedBy")
        self.gridLayout_4.addWidget(self.label_recordedBy, 0, 1, 1, 1)
        self.lineEdit_associatedCollectors = QtWidgets.QLineEdit(self.groupGrid_event)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_associatedCollectors.sizePolicy().hasHeightForWidth())
        self.lineEdit_associatedCollectors.setSizePolicy(sizePolicy)
        self.lineEdit_associatedCollectors.setObjectName("lineEdit_associatedCollectors")
        self.gridLayout_4.addWidget(self.lineEdit_associatedCollectors, 1, 2, 1, 1)
        self.verticalLayout_9.addWidget(self.groupGrid_event)
        self.groupBox = QtWidgets.QGroupBox(self.StackedWidgetPage2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setContentsMargins(0, 6, 9, 0)
        self.gridLayout_3.setVerticalSpacing(3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_municipality = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_municipality.setObjectName("lineEdit_municipality")
        self.gridLayout_3.addWidget(self.lineEdit_municipality, 10, 0, 1, 1)
        self.lineEdit_path = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.gridLayout_3.addWidget(self.lineEdit_path, 10, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_associatedTaxa = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_associatedTaxa.sizePolicy().hasHeightForWidth())
        self.label_associatedTaxa.setSizePolicy(sizePolicy)
        self.label_associatedTaxa.setObjectName("label_associatedTaxa")
        self.horizontalLayout_7.addWidget(self.label_associatedTaxa)
        self.button_associatedTaxa = QtWidgets.QToolButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_associatedTaxa.sizePolicy().hasHeightForWidth())
        self.button_associatedTaxa.setSizePolicy(sizePolicy)
        self.button_associatedTaxa.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.button_associatedTaxa.setSizeIncrement(QtCore.QSize(0, 0))
        self.button_associatedTaxa.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rc_/plus-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_associatedTaxa.setIcon(icon)
        self.button_associatedTaxa.setObjectName("button_associatedTaxa")
        self.horizontalLayout_7.addWidget(self.button_associatedTaxa, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.lineEdit_associatedTaxa = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_associatedTaxa.setObjectName("lineEdit_associatedTaxa")
        self.horizontalLayout_7.addWidget(self.lineEdit_associatedTaxa)
        self.horizontalLayout_7.setStretch(2, 10)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 0, 0, 1, 2)
        self.label_stateProvince = QtWidgets.QLabel(self.groupBox)
        self.label_stateProvince.setObjectName("label_stateProvince")
        self.gridLayout_3.addWidget(self.label_stateProvince, 5, 0, 1, 1)
        self.lineEdit_county = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_county.setObjectName("lineEdit_county")
        self.gridLayout_3.addWidget(self.lineEdit_county, 6, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_locality = QtWidgets.QLabel(self.groupBox)
        self.label_locality.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_locality.setObjectName("label_locality")
        self.horizontalLayout_6.addWidget(self.label_locality)
        self.toolButton_reverseGeolocate = QtWidgets.QToolButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_reverseGeolocate.sizePolicy().hasHeightForWidth())
        self.toolButton_reverseGeolocate.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/rc_/map-pin.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_reverseGeolocate.setIcon(icon1)
        self.toolButton_reverseGeolocate.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_reverseGeolocate.setObjectName("toolButton_reverseGeolocate")
        self.horizontalLayout_6.addWidget(self.toolButton_reverseGeolocate)
        self.plainTextEdit_locality = QtWidgets.QPlainTextEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_locality.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_locality.setSizePolicy(sizePolicy)
        self.plainTextEdit_locality.setMinimumSize(QtCore.QSize(0, 45))
        self.plainTextEdit_locality.setMaximumSize(QtCore.QSize(16777215, 50))
        self.plainTextEdit_locality.setBackgroundVisible(False)
        self.plainTextEdit_locality.setObjectName("plainTextEdit_locality")
        self.horizontalLayout_6.addWidget(self.plainTextEdit_locality)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 2, 0, 1, 2)
        self.label_path = QtWidgets.QLabel(self.groupBox)
        self.label_path.setObjectName("label_path")
        self.gridLayout_3.addWidget(self.label_path, 9, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_habitat = QtWidgets.QLabel(self.groupBox)
        self.label_habitat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_habitat.setObjectName("label_habitat")
        self.horizontalLayout_8.addWidget(self.label_habitat)
        self.lineEdit_habitat = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_habitat.setObjectName("lineEdit_habitat")
        self.horizontalLayout_8.addWidget(self.lineEdit_habitat)
        self.label_locationNotes = QtWidgets.QLabel(self.groupBox)
        self.label_locationNotes.setObjectName("label_locationNotes")
        self.horizontalLayout_8.addWidget(self.label_locationNotes, 0, QtCore.Qt.AlignRight)
        self.lineEdit_locationNotes = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_locationNotes.setObjectName("lineEdit_locationNotes")
        self.horizontalLayout_8.addWidget(self.lineEdit_locationNotes)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 1, 0, 1, 2)
        self.label_county = QtWidgets.QLabel(self.groupBox)
        self.label_county.setObjectName("label_county")
        self.gridLayout_3.addWidget(self.label_county, 5, 1, 1, 1)
        self.label_municipality = QtWidgets.QLabel(self.groupBox)
        self.label_municipality.setObjectName("label_municipality")
        self.gridLayout_3.addWidget(self.label_municipality, 9, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_decimalLongitude = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_decimalLongitude.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lineEdit_decimalLongitude.setObjectName("lineEdit_decimalLongitude")
        self.gridLayout_2.addWidget(self.lineEdit_decimalLongitude, 1, 1, 1, 1)
        self.label_latitude = QtWidgets.QLabel(self.groupBox)
        self.label_latitude.setObjectName("label_latitude")
        self.gridLayout_2.addWidget(self.label_latitude, 0, 0, 1, 1)
        self.lineEdit_coordinateUncertaintyInMeters = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_coordinateUncertaintyInMeters.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lineEdit_coordinateUncertaintyInMeters.setObjectName("lineEdit_coordinateUncertaintyInMeters")
        self.gridLayout_2.addWidget(self.lineEdit_coordinateUncertaintyInMeters, 1, 2, 1, 1)
        self.label_uncertainty = QtWidgets.QLabel(self.groupBox)
        self.label_uncertainty.setObjectName("label_uncertainty")
        self.gridLayout_2.addWidget(self.label_uncertainty, 0, 2, 1, 1)
        self.lineEdit_decimalLatitude = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_decimalLatitude.setText("")
        self.lineEdit_decimalLatitude.setFrame(True)
        self.lineEdit_decimalLatitude.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lineEdit_decimalLatitude.setObjectName("lineEdit_decimalLatitude")
        self.gridLayout_2.addWidget(self.lineEdit_decimalLatitude, 1, 0, 1, 1)
        self.label_longitude = QtWidgets.QLabel(self.groupBox)
        self.label_longitude.setObjectName("label_longitude")
        self.gridLayout_2.addWidget(self.label_longitude, 0, 1, 1, 1)
        self.label_elevation = QtWidgets.QLabel(self.groupBox)
        self.label_elevation.setObjectName("label_elevation")
        self.gridLayout_2.addWidget(self.label_elevation, 0, 3, 1, 1)
        self.lineEdit_minimumElevationInMeters = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_minimumElevationInMeters.setText("")
        self.lineEdit_minimumElevationInMeters.setObjectName("lineEdit_minimumElevationInMeters")
        self.gridLayout_2.addWidget(self.lineEdit_minimumElevationInMeters, 1, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 3, 0, 1, 2)
        self.lineEdit_stateProvince = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_stateProvince.setObjectName("lineEdit_stateProvince")
        self.gridLayout_3.addWidget(self.lineEdit_stateProvince, 6, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.verticalLayout_9)
        self.formView.addWidget(self.StackedWidgetPage2)
        self.StackedWidgetPage3 = QtWidgets.QWidget()
        self.StackedWidgetPage3.setObjectName("StackedWidgetPage3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.StackedWidgetPage3)
        self.verticalLayout_4.setContentsMargins(0, 3, 0, 3)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_newSpecimen_2 = QtWidgets.QPushButton(self.StackedWidgetPage3)
        self.pushButton_newSpecimen_2.setObjectName("pushButton_newSpecimen_2")
        self.horizontalLayout_10.addWidget(self.pushButton_newSpecimen_2)
        self.pushButton_duplicateSpecimen = QtWidgets.QPushButton(self.StackedWidgetPage3)
        self.pushButton_duplicateSpecimen.setObjectName("pushButton_duplicateSpecimen")
        self.horizontalLayout_10.addWidget(self.pushButton_duplicateSpecimen)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.checkBox_deleteRecord = QtWidgets.QCheckBox(self.StackedWidgetPage3)
        self.checkBox_deleteRecord.setText("")
        self.checkBox_deleteRecord.setObjectName("checkBox_deleteRecord")
        self.horizontalLayout_10.addWidget(self.checkBox_deleteRecord)
        self.pushButton_deleteRecord = QtWidgets.QPushButton(self.StackedWidgetPage3)
        self.pushButton_deleteRecord.setEnabled(False)
        self.pushButton_deleteRecord.setObjectName("pushButton_deleteRecord")
        self.horizontalLayout_10.addWidget(self.pushButton_deleteRecord)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.groupBox_specimen = QtWidgets.QGroupBox(self.StackedWidgetPage3)
        self.groupBox_specimen.setObjectName("groupBox_specimen")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_specimen)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(-1, 6, -1, -1)
        self.formLayout.setVerticalSpacing(3)
        self.formLayout.setObjectName("formLayout")
        self.label_otherCatalogNumber = QtWidgets.QLabel(self.groupBox_specimen)
        self.label_otherCatalogNumber.setObjectName("label_otherCatalogNumber")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_otherCatalogNumber)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit_otherCatalogNumbers = QtWidgets.QLineEdit(self.groupBox_specimen)
        self.lineEdit_otherCatalogNumbers.setEnabled(False)
        self.lineEdit_otherCatalogNumbers.setObjectName("lineEdit_otherCatalogNumbers")
        self.horizontalLayout_9.addWidget(self.lineEdit_otherCatalogNumbers)
        self.label_catalogNumber = QtWidgets.QLabel(self.groupBox_specimen)
        self.label_catalogNumber.setObjectName("label_catalogNumber")
        self.horizontalLayout_9.addWidget(self.label_catalogNumber, 0, QtCore.Qt.AlignRight)
        self.lineEdit_catalogNumber = QtWidgets.QLineEdit(self.groupBox_specimen)
        self.lineEdit_catalogNumber.setObjectName("lineEdit_catalogNumber")
        self.horizontalLayout_9.addWidget(self.lineEdit_catalogNumber)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.label_sciName = QtWidgets.QLabel(self.groupBox_specimen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sciName.sizePolicy().hasHeightForWidth())
        self.label_sciName.setSizePolicy(sizePolicy)
        self.label_sciName.setObjectName("label_sciName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_sciName)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolButton_verifyTaxonomy = QtWidgets.QToolButton(self.groupBox_specimen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_verifyTaxonomy.sizePolicy().hasHeightForWidth())
        self.toolButton_verifyTaxonomy.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/rc_/check-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_verifyTaxonomy.setIcon(icon2)
        self.toolButton_verifyTaxonomy.setIconSize(QtCore.QSize(25, 18))
        self.toolButton_verifyTaxonomy.setObjectName("toolButton_verifyTaxonomy")
        self.horizontalLayout_2.addWidget(self.toolButton_verifyTaxonomy)
        self.lineEdit_sciName = QtWidgets.QLineEdit(self.groupBox_specimen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_sciName.sizePolicy().hasHeightForWidth())
        self.lineEdit_sciName.setSizePolicy(sizePolicy)
        self.lineEdit_sciName.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_sciName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_sciName.setObjectName("lineEdit_sciName")
        self.horizontalLayout_2.addWidget(self.lineEdit_sciName)
        self.label_sciNameAuthority = QtWidgets.QLabel(self.groupBox_specimen)
        self.label_sciNameAuthority.setObjectName("label_sciNameAuthority")
        self.horizontalLayout_2.addWidget(self.label_sciNameAuthority, 0, QtCore.Qt.AlignRight)
        self.lineEdit_sciNameAuthority = QtWidgets.QLineEdit(self.groupBox_specimen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_sciNameAuthority.sizePolicy().hasHeightForWidth())
        self.lineEdit_sciNameAuthority.setSizePolicy(sizePolicy)
        self.lineEdit_sciNameAuthority.setObjectName("lineEdit_sciNameAuthority")
        self.horizontalLayout_2.addWidget(self.lineEdit_sciNameAuthority)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 2)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.occurrenceRemarksLabel = QtWidgets.QLabel(self.groupBox_specimen)
        self.occurrenceRemarksLabel.setObjectName("occurrenceRemarksLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.occurrenceRemarksLabel)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_occurrenceRemarks = QtWidgets.QLineEdit(self.groupBox_specimen)
        self.lineEdit_occurrenceRemarks.setObjectName("lineEdit_occurrenceRemarks")
        self.horizontalLayout_4.addWidget(self.lineEdit_occurrenceRemarks)
        self.label_substrate = QtWidgets.QLabel(self.groupBox_specimen)
        self.label_substrate.setObjectName("label_substrate")
        self.horizontalLayout_4.addWidget(self.label_substrate, 0, QtCore.Qt.AlignRight)
        self.lineEdit_substrate = QtWidgets.QLineEdit(self.groupBox_specimen)
        self.lineEdit_substrate.setObjectName("lineEdit_substrate")
        self.horizontalLayout_4.addWidget(self.lineEdit_substrate)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_reproductiveCondition = QtWidgets.QLabel(self.groupBox_specimen)
        self.label_reproductiveCondition.setObjectName("label_reproductiveCondition")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_reproductiveCondition)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.comboBox_reproductiveCondition = QtWidgets.QComboBox(self.groupBox_specimen)
        self.comboBox_reproductiveCondition.setObjectName("comboBox_reproductiveCondition")
        self.comboBox_reproductiveCondition.addItem("")
        self.comboBox_reproductiveCondition.setItemText(0, "")
        self.comboBox_reproductiveCondition.addItem("")
        self.comboBox_reproductiveCondition.addItem("")
        self.comboBox_reproductiveCondition.addItem("")
        self.comboBox_reproductiveCondition.addItem("")
        self.comboBox_reproductiveCondition.addItem("")
        self.comboBox_reproductiveCondition.addItem("")
        self.comboBox_reproductiveCondition.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_reproductiveCondition)
        self.label_individualCount = QtWidgets.QLabel(self.groupBox_specimen)
        self.label_individualCount.setObjectName("label_individualCount")
        self.horizontalLayout_5.addWidget(self.label_individualCount, 0, QtCore.Qt.AlignRight)
        self.spinBox_individualCount = QtWidgets.QSpinBox(self.groupBox_specimen)
        self.spinBox_individualCount.setMaximum(99999)
        self.spinBox_individualCount.setProperty("value", 0)
        self.spinBox_individualCount.setObjectName("spinBox_individualCount")
        self.horizontalLayout_5.addWidget(self.spinBox_individualCount)
        self.checkBox_establishmentMeans = QtWidgets.QCheckBox(self.groupBox_specimen)
        self.checkBox_establishmentMeans.setObjectName("checkBox_establishmentMeans")
        self.horizontalLayout_5.addWidget(self.checkBox_establishmentMeans)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(3, 1)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_identificationRemarks = QtWidgets.QLabel(self.groupBox_specimen)
        self.label_identificationRemarks.setObjectName("label_identificationRemarks")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_identificationRemarks)
        self.plainTextEdit_identificationRemarks = QtWidgets.QPlainTextEdit(self.groupBox_specimen)
        self.plainTextEdit_identificationRemarks.setMinimumSize(QtCore.QSize(0, 45))
        self.plainTextEdit_identificationRemarks.setMaximumSize(QtCore.QSize(16777215, 50))
        self.plainTextEdit_identificationRemarks.setObjectName("plainTextEdit_identificationRemarks")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit_identificationRemarks)
        self.label_identificationReferences = QtWidgets.QLabel(self.groupBox_specimen)
        self.label_identificationReferences.setObjectName("label_identificationReferences")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_identificationReferences)
        self.plainTextEdit_identificationReferences = QtWidgets.QPlainTextEdit(self.groupBox_specimen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_identificationReferences.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_identificationReferences.setSizePolicy(sizePolicy)
        self.plainTextEdit_identificationReferences.setMinimumSize(QtCore.QSize(0, 45))
        self.plainTextEdit_identificationReferences.setMaximumSize(QtCore.QSize(16777215, 50))
        self.plainTextEdit_identificationReferences.setObjectName("plainTextEdit_identificationReferences")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit_identificationReferences)
        self.verticalLayout_4.addWidget(self.groupBox_specimen)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.formView.addWidget(self.StackedWidgetPage3)
        self.horizontalLayout_3.addWidget(self.formView)
        self.gridLayout_7.addLayout(self.horizontalLayout_3, 0, 2, 3, 1)
        self.value_zoomLevel = QtWidgets.QSlider(self.centralwidget)
        self.value_zoomLevel.setMinimumSize(QtCore.QSize(0, 0))
        self.value_zoomLevel.setMaximumSize(QtCore.QSize(150, 16777215))
        self.value_zoomLevel.setToolTipDuration(2)
        self.value_zoomLevel.setMinimum(10)
        self.value_zoomLevel.setMaximum(200)
        self.value_zoomLevel.setSingleStep(5)
        self.value_zoomLevel.setPageStep(20)
        self.value_zoomLevel.setProperty("value", 100)
        self.value_zoomLevel.setOrientation(QtCore.Qt.Horizontal)
        self.value_zoomLevel.setInvertedAppearance(False)
        self.value_zoomLevel.setInvertedControls(False)
        self.value_zoomLevel.setObjectName("value_zoomLevel")
        self.gridLayout_7.addWidget(self.value_zoomLevel, 2, 0, 1, 1)
        self.label_zoomLevel = QtWidgets.QLabel(self.centralwidget)
        self.label_zoomLevel.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_zoomLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_zoomLevel.setObjectName("label_zoomLevel")
        self.gridLayout_7.addWidget(self.label_zoomLevel, 1, 0, 1, 1)
        self.pdf_preview = PDFViewer(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pdf_preview.sizePolicy().hasHeightForWidth())
        self.pdf_preview.setSizePolicy(sizePolicy)
        self.pdf_preview.setMinimumSize(QtCore.QSize(0, 0))
        self.pdf_preview.setText("")
        self.pdf_preview.setObjectName("pdf_preview")
        self.gridLayout_7.addWidget(self.pdf_preview, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem6, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_7)
        self.lower_horizontalLayout = QtWidgets.QHBoxLayout()
        self.lower_horizontalLayout.setObjectName("lower_horizontalLayout")
        self.tree_widget = QtWidgets.QTreeWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_widget.sizePolicy().hasHeightForWidth())
        self.tree_widget.setSizePolicy(sizePolicy)
        self.tree_widget.setMinimumSize(QtCore.QSize(150, 0))
        self.tree_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tree_widget.setSizeIncrement(QtCore.QSize(0, 0))
        self.tree_widget.setBaseSize(QtCore.QSize(150, 0))
        self.tree_widget.setMouseTracking(False)
        self.tree_widget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tree_widget.setStyleSheet("font: 12pt \"Cantarell\";")
        self.tree_widget.setFrameShape(QtWidgets.QFrame.Panel)
        self.tree_widget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tree_widget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tree_widget.setProperty("showDropIndicator", False)
        self.tree_widget.setAlternatingRowColors(True)
        self.tree_widget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tree_widget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tree_widget.setExpandsOnDoubleClick(True)
        self.tree_widget.setObjectName("tree_widget")
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_widget)
        self.lower_horizontalLayout.addWidget(self.tree_widget)
        self.table_view = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_view.sizePolicy().hasHeightForWidth())
        self.table_view.setSizePolicy(sizePolicy)
        self.table_view.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.table_view.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.table_view.setAlternatingRowColors(False)
        self.table_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_view.setIconSize(QtCore.QSize(100, 100))
        self.table_view.setGridStyle(QtCore.Qt.DashLine)
        self.table_view.setSortingEnabled(True)
        self.table_view.setObjectName("table_view")
        self.table_view.verticalHeader().setCascadingSectionResizes(False)
        self.table_view.verticalHeader().setSortIndicatorShown(False)
        self.lower_horizontalLayout.addWidget(self.table_view)
        self.verticalLayout.addLayout(self.lower_horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 940, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.left_toolBar = QtWidgets.QToolBar(MainWindow)
        self.left_toolBar.setObjectName("left_toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.left_toolBar)
        self.right_toolBar = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_toolBar.sizePolicy().hasHeightForWidth())
        self.right_toolBar.setSizePolicy(sizePolicy)
        self.right_toolBar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.right_toolBar.setObjectName("right_toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.right_toolBar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/rc_/file-text.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Open.setIcon(icon3)
        self.action_Open.setObjectName("action_Open")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/rc_/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Exit.setIcon(icon4)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Verify_Taxonomy = QtWidgets.QAction(MainWindow)
        self.action_Verify_Taxonomy.setIcon(icon2)
        self.action_Verify_Taxonomy.setObjectName("action_Verify_Taxonomy")
        self.action_Reverse_Geolocate = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/rc_/map-pin.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_Reverse_Geolocate.setIcon(icon5)
        self.action_Reverse_Geolocate.setObjectName("action_Reverse_Geolocate")
        self.action_Save_As = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/rc_/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Save_As.setIcon(icon6)
        self.action_Save_As.setObjectName("action_Save_As")
        self.action_New_Records = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/rc_/file-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_New_Records.setIcon(icon7)
        self.action_New_Records.setObjectName("action_New_Records")
        self.action_undo = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/rc_/corner-down-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/icons/corner-down-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_undo.setIcon(icon8)
        self.action_undo.setObjectName("action_undo")
        self.action_redo = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/rc_/corner-down-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":/icons/corner-down-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_redo.setIcon(icon9)
        self.action_redo.setObjectName("action_redo")
        self.action_Settings = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/rc_/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Settings.setIcon(icon10)
        self.action_Settings.setObjectName("action_Settings")
        self.action_Export_Labels = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/rc_/tag.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Export_Labels.setIcon(icon11)
        self.action_Export_Labels.setObjectName("action_Export_Labels")
        self.actionTestFunction = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/rc_/circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTestFunction.setIcon(icon12)
        self.actionTestFunction.setObjectName("actionTestFunction")
        self.action_Verify_All = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/rc_/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Verify_All.setIcon(icon13)
        self.action_Verify_All.setObjectName("action_Verify_All")
        self.action_Export_Records = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/rc_/truck.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Export_Records.setIcon(icon14)
        self.action_Export_Records.setObjectName("action_Export_Records")
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.action_New_Records)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Exit)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.left_toolBar.addAction(self.action_New_Records)
        self.left_toolBar.addAction(self.action_Open)
        self.left_toolBar.addAction(self.action_Settings)
        self.left_toolBar.addSeparator()
        self.left_toolBar.addAction(self.action_undo)
        self.left_toolBar.addAction(self.action_redo)
        self.left_toolBar.addSeparator()
        self.left_toolBar.addAction(self.action_Verify_All)
        self.left_toolBar.addAction(self.action_Export_Records)
        self.right_toolBar.addSeparator()
        self.right_toolBar.addAction(self.action_Exit)
        self.label_associatedTaxa.setBuddy(self.button_associatedTaxa)
        self.label_habitat.setBuddy(self.lineEdit_habitat)
        self.label_locationNotes.setBuddy(self.lineEdit_locationNotes)

        self.retranslateUi(MainWindow)
        self.formView.setCurrentIndex(0)
        self.tree_widget.currentItemChanged['QTreeWidgetItem*','QTreeWidgetItem*'].connect(MainWindow.updateTableView)
        self.table_view.clicked['QModelIndex'].connect(MainWindow.updatePreview)
        self.radioButton_applySelectSites.toggled['bool'].connect(self.verticalFrame_2.setEnabled)
        self.radioButton_applySelectSites.toggled['bool'].connect(self.treeWidget_sitesToApply.setEnabled)
        self.radioButton_applySelectSites.toggled['bool'].connect(self.toolButton_sitesToApply_SelectAll.setEnabled)
        self.radioButton_applySelectSites.toggled['bool'].connect(self.toolButton_sitesToApply_SelectNone.setEnabled)
        self.checkBox_delSite.toggled['bool'].connect(self.pushButton_deleteSite.setEnabled)
        self.checkBox_deleteRecord.toggled['bool'].connect(self.pushButton_deleteRecord.setEnabled)
        self.value_zoomLevel.valueChanged['int'].connect(MainWindow.updatePreviewZoom)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.plainTextEdit_labelProject, self.plainTextEdit_fieldNotes)
        MainWindow.setTabOrder(self.plainTextEdit_fieldNotes, self.lineEdit_eventRemarks)
        MainWindow.setTabOrder(self.lineEdit_eventRemarks, self.lineEdit_samplingEffort)
        MainWindow.setTabOrder(self.lineEdit_samplingEffort, self.pushButton_newSite)
        MainWindow.setTabOrder(self.pushButton_newSite, self.lineEdit_recordedBy)
        MainWindow.setTabOrder(self.lineEdit_recordedBy, self.lineEdit_associatedCollectors)
        MainWindow.setTabOrder(self.lineEdit_associatedCollectors, self.button_associatedTaxa)
        MainWindow.setTabOrder(self.button_associatedTaxa, self.lineEdit_associatedTaxa)
        MainWindow.setTabOrder(self.lineEdit_associatedTaxa, self.lineEdit_habitat)
        MainWindow.setTabOrder(self.lineEdit_habitat, self.lineEdit_locationNotes)
        MainWindow.setTabOrder(self.lineEdit_locationNotes, self.toolButton_reverseGeolocate)
        MainWindow.setTabOrder(self.toolButton_reverseGeolocate, self.plainTextEdit_locality)
        MainWindow.setTabOrder(self.plainTextEdit_locality, self.lineEdit_decimalLatitude)
        MainWindow.setTabOrder(self.lineEdit_decimalLatitude, self.lineEdit_decimalLongitude)
        MainWindow.setTabOrder(self.lineEdit_decimalLongitude, self.lineEdit_coordinateUncertaintyInMeters)
        MainWindow.setTabOrder(self.lineEdit_coordinateUncertaintyInMeters, self.lineEdit_minimumElevationInMeters)
        MainWindow.setTabOrder(self.lineEdit_minimumElevationInMeters, self.lineEdit_stateProvince)
        MainWindow.setTabOrder(self.lineEdit_stateProvince, self.lineEdit_county)
        MainWindow.setTabOrder(self.lineEdit_county, self.lineEdit_municipality)
        MainWindow.setTabOrder(self.lineEdit_municipality, self.lineEdit_path)
        MainWindow.setTabOrder(self.lineEdit_path, self.lineEdit_sciName)
        MainWindow.setTabOrder(self.lineEdit_sciName, self.toolButton_verifyTaxonomy)
        MainWindow.setTabOrder(self.toolButton_verifyTaxonomy, self.lineEdit_sciNameAuthority)
        MainWindow.setTabOrder(self.lineEdit_sciNameAuthority, self.lineEdit_occurrenceRemarks)
        MainWindow.setTabOrder(self.lineEdit_occurrenceRemarks, self.lineEdit_substrate)
        MainWindow.setTabOrder(self.lineEdit_substrate, self.comboBox_reproductiveCondition)
        MainWindow.setTabOrder(self.comboBox_reproductiveCondition, self.spinBox_individualCount)
        MainWindow.setTabOrder(self.spinBox_individualCount, self.checkBox_establishmentMeans)
        MainWindow.setTabOrder(self.checkBox_establishmentMeans, self.plainTextEdit_identificationRemarks)
        MainWindow.setTabOrder(self.plainTextEdit_identificationRemarks, self.plainTextEdit_identificationReferences)
        MainWindow.setTabOrder(self.plainTextEdit_identificationReferences, self.lineEdit_default_recordedBy)
        MainWindow.setTabOrder(self.lineEdit_default_recordedBy, self.dateEdit_default_eventDate)
        MainWindow.setTabOrder(self.dateEdit_default_eventDate, self.treeWidget_sitesToApply)
        MainWindow.setTabOrder(self.treeWidget_sitesToApply, self.toolButton_sitesToApply_SelectNone)
        MainWindow.setTabOrder(self.toolButton_sitesToApply_SelectNone, self.radioButton_applySelectSites)
        MainWindow.setTabOrder(self.radioButton_applySelectSites, self.toolButton_sitesToApply_SelectAll)
        MainWindow.setTabOrder(self.toolButton_sitesToApply_SelectAll, self.pushButton_newSpecimen_2)
        MainWindow.setTabOrder(self.pushButton_newSpecimen_2, self.pushButton_duplicateSpecimen)
        MainWindow.setTabOrder(self.pushButton_duplicateSpecimen, self.checkBox_deleteRecord)
        MainWindow.setTabOrder(self.checkBox_deleteRecord, self.pushButton_deleteRecord)
        MainWindow.setTabOrder(self.pushButton_deleteRecord, self.lineEdit_otherCatalogNumbers)
        MainWindow.setTabOrder(self.lineEdit_otherCatalogNumbers, self.lineEdit_catalogNumber)
        MainWindow.setTabOrder(self.lineEdit_catalogNumber, self.checkBox_delSite)
        MainWindow.setTabOrder(self.checkBox_delSite, self.dateEdit_eventDate)
        MainWindow.setTabOrder(self.dateEdit_eventDate, self.pushButton_deleteSite)
        MainWindow.setTabOrder(self.pushButton_deleteSite, self.formView)
        MainWindow.setTabOrder(self.formView, self.lineEdit_default_associatedCollectors)
        MainWindow.setTabOrder(self.lineEdit_default_associatedCollectors, self.groupBox_newSite_defaults)
        MainWindow.setTabOrder(self.groupBox_newSite_defaults, self.pushButton_newSpecimen)
        MainWindow.setTabOrder(self.pushButton_newSpecimen, self.radioButton_applyAllRecords)
        MainWindow.setTabOrder(self.radioButton_applyAllRecords, self.value_zoomLevel)
        MainWindow.setTabOrder(self.value_zoomLevel, self.tree_widget)
        MainWindow.setTabOrder(self.tree_widget, self.table_view)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "collDesk"))
        self.pushButton_newSite.setText(_translate("MainWindow", "Add new site"))
        self.gridGroupBox.setTitle(_translate("MainWindow", "Trip"))
        self.label_samplingEffort.setText(_translate("MainWindow", "Sampling Effort "))
        self.label_eventRemarks.setText(_translate("MainWindow", "Event Remarks"))
        self.label_fieldNotes.setText(_translate("MainWindow", "Field Notes "))
        self.label_labelProject.setText(_translate("MainWindow", "Project Name"))
        self.radioButton_applyAllRecords.setText(_translate("MainWindow", "Apply to all records "))
        self.radioButton_applySelectSites.setText(_translate("MainWindow", "Apply to select sites"))
        __sortingEnabled = self.treeWidget_sitesToApply.isSortingEnabled()
        self.treeWidget_sitesToApply.setSortingEnabled(False)
        self.treeWidget_sitesToApply.topLevelItem(0).setText(0, _translate("MainWindow", "Site 1"))
        self.treeWidget_sitesToApply.setSortingEnabled(__sortingEnabled)
        self.toolButton_sitesToApply_SelectNone.setText(_translate("MainWindow", "select none"))
        self.toolButton_sitesToApply_SelectAll.setText(_translate("MainWindow", "select all"))
        self.groupBox_newSite_defaults.setTitle(_translate("MainWindow", "Defaults (for new sites)"))
        self.label_default_eventDate.setText(_translate("MainWindow", "Date (of collection)"))
        self.label_default_recordedBy.setText(_translate("MainWindow", "Primary Collector"))
        self.label_default_associatedCollectors.setText(_translate("MainWindow", "Associated Collectors (comma seperated)"))
        self.dateEdit_default_eventDate.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.pushButton_newSpecimen.setText(_translate("MainWindow", "Add specimen to this site"))
        self.pushButton_deleteSite.setText(_translate("MainWindow", "Delete site"))
        self.groupGrid_event.setTitle(_translate("MainWindow", "Event"))
        self.dateEdit_eventDate.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.label_associatedCollectors.setText(_translate("MainWindow", "Associated Collectors (comma seperated)"))
        self.label_eventDate.setText(_translate("MainWindow", "Date (of collection)"))
        self.label_recordedBy.setText(_translate("MainWindow", "Primary Collector"))
        self.groupBox.setTitle(_translate("MainWindow", "Location"))
        self.label_associatedTaxa.setText(_translate("MainWindow", "Associated Taxa"))
        self.label_stateProvince.setText(_translate("MainWindow", " State/Province"))
        self.label_locality.setText(_translate("MainWindow", "Locality"))
        self.toolButton_reverseGeolocate.setText(_translate("MainWindow", "..."))
        self.label_path.setText(_translate("MainWindow", "Path (road or trail name)"))
        self.label_habitat.setText(_translate("MainWindow", "Habitat"))
        self.label_locationNotes.setText(_translate("MainWindow", "Location Notes"))
        self.label_county.setText(_translate("MainWindow", "County"))
        self.label_municipality.setText(_translate("MainWindow", "Municipality"))
        self.label_latitude.setText(_translate("MainWindow", "Latitude (decimal deg)"))
        self.label_uncertainty.setText(_translate("MainWindow", "Uncertainty (m)"))
        self.label_longitude.setText(_translate("MainWindow", "Longitude (decimal deg)"))
        self.label_elevation.setText(_translate("MainWindow", "Elevation (m)"))
        self.pushButton_newSpecimen_2.setText(_translate("MainWindow", "Add specimen to this site"))
        self.pushButton_duplicateSpecimen.setText(_translate("MainWindow", "Duplicate this record"))
        self.pushButton_deleteRecord.setText(_translate("MainWindow", "Delete record"))
        self.groupBox_specimen.setTitle(_translate("MainWindow", "Specimen"))
        self.label_otherCatalogNumber.setText(_translate("MainWindow", "Field Number"))
        self.label_catalogNumber.setText(_translate("MainWindow", "Catalog Number"))
        self.label_sciName.setText(_translate("MainWindow", "Scientific Name"))
        self.toolButton_verifyTaxonomy.setText(_translate("MainWindow", "..."))
        self.label_sciNameAuthority.setText(_translate("MainWindow", "Authority"))
        self.occurrenceRemarksLabel.setText(_translate("MainWindow", "Occurrence Remarks"))
        self.label_substrate.setText(_translate("MainWindow", "Substrate"))
        self.label_reproductiveCondition.setText(_translate("MainWindow", "Reproductive Condition"))
        self.comboBox_reproductiveCondition.setItemText(1, _translate("MainWindow", "Vegetative"))
        self.comboBox_reproductiveCondition.setItemText(2, _translate("MainWindow", "Reproductive"))
        self.comboBox_reproductiveCondition.setItemText(3, _translate("MainWindow", "    Early reproductive"))
        self.comboBox_reproductiveCondition.setItemText(4, _translate("MainWindow", "    Peak reproductive"))
        self.comboBox_reproductiveCondition.setItemText(5, _translate("MainWindow", "    Late reproductive"))
        self.comboBox_reproductiveCondition.setItemText(6, _translate("MainWindow", "    Fruit / seed bearing"))
        self.comboBox_reproductiveCondition.setItemText(7, _translate("MainWindow", "N/A"))
        self.label_individualCount.setText(_translate("MainWindow", "Est. Qty"))
        self.checkBox_establishmentMeans.setText(_translate("MainWindow", "Cultivated"))
        self.label_identificationRemarks.setText(_translate("MainWindow", "Identification Remarks"))
        self.label_identificationReferences.setText(_translate("MainWindow", "Identification References "))
        self.label_zoomLevel.setText(_translate("MainWindow", "TextLabel"))
        self.tree_widget.headerItem().setText(0, _translate("MainWindow", "Sites"))
        __sortingEnabled = self.tree_widget.isSortingEnabled()
        self.tree_widget.setSortingEnabled(False)
        self.tree_widget.topLevelItem(0).setText(0, _translate("MainWindow", "All Records"))
        self.tree_widget.setSortingEnabled(__sortingEnabled)
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.left_toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.right_toolBar.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.action_Open.setText(_translate("MainWindow", "&Open"))
        self.action_Open.setToolTip(_translate("MainWindow", "Open a CSV file"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))
        self.action_Verify_Taxonomy.setText(_translate("MainWindow", "&Verify Taxonomy"))
        self.action_Verify_Taxonomy.setToolTip(_translate("MainWindow", "align scientific names & retrieve authorities"))
        self.action_Reverse_Geolocate.setText(_translate("MainWindow", "&Reverse Geolocate"))
        self.action_Reverse_Geolocate.setToolTip(_translate("MainWindow", "Use GPS coordinates to prepend locality details"))
        self.action_Save_As.setText(_translate("MainWindow", "&Save As"))
        self.action_New_Records.setText(_translate("MainWindow", "&New Records"))
        self.action_New_Records.setToolTip(_translate("MainWindow", "Generate a new, empty record list"))
        self.action_undo.setText(_translate("MainWindow", "&undo"))
        self.action_undo.setToolTip(_translate("MainWindow", "undo last major action"))
        self.action_redo.setText(_translate("MainWindow", "&Redo"))
        self.action_redo.setToolTip(_translate("MainWindow", "redo last major action"))
        self.action_Settings.setText(_translate("MainWindow", "&Settings"))
        self.action_Settings.setToolTip(_translate("MainWindow", "Settings and preferences"))
        self.action_Export_Labels.setText(_translate("MainWindow", "&Export_Labels"))
        self.actionTestFunction.setText(_translate("MainWindow", "&TestFunction"))
        self.actionTestFunction.setToolTip(_translate("MainWindow", "Test a function"))
        self.action_Verify_All.setText(_translate("MainWindow", "&ProcessSelectedRecords"))
        self.action_Verify_All.setToolTip(_translate("MainWindow", "Refine All Selected Records"))
        self.action_Export_Records.setText(_translate("MainWindow", "&Export Records"))
        self.action_Export_Records.setToolTip(_translate("MainWindow", "Export your records for database upload and label printing"))

from ui.formview import formView
from ui.pdfviewer import PDFViewer
import Resources_rc
