# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/settingsUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_settingsWindow(object):
    def setupUi(self, settingsWindow):
        settingsWindow.setObjectName("settingsWindow")
        settingsWindow.resize(539, 483)
        settingsWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(settingsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.upperHorizontalLayout = QtWidgets.QHBoxLayout()
        self.upperHorizontalLayout.setObjectName("upperHorizontalLayout")
        self.selectionWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionWidget.sizePolicy().hasHeightForWidth())
        self.selectionWidget.setSizePolicy(sizePolicy)
        self.selectionWidget.setLineWidth(1)
        self.selectionWidget.setObjectName("selectionWidget")
        item = QtWidgets.QListWidgetItem()
        self.selectionWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.selectionWidget.addItem(item)
        self.upperHorizontalLayout.addWidget(self.selectionWidget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.labelPrefPage = QtWidgets.QWidget()
        self.labelPrefPage.setObjectName("labelPrefPage")
        self.gridLayout = QtWidgets.QGridLayout(self.labelPrefPage)
        self.gridLayout.setObjectName("gridLayout")
        self.labelDimentionsGroup = QtWidgets.QGroupBox(self.labelPrefPage)
        self.labelDimentionsGroup.setObjectName("labelDimentionsGroup")
        self.formLayout_4 = QtWidgets.QFormLayout(self.labelDimentionsGroup)
        self.formLayout_4.setObjectName("formLayout_4")
        self.xLabel = QtWidgets.QLabel(self.labelDimentionsGroup)
        self.xLabel.setObjectName("xLabel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.xLabel)
        self.value_X = QtWidgets.QSpinBox(self.labelDimentionsGroup)
        self.value_X.setObjectName("value_X")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.value_X)
        self.yLabel = QtWidgets.QLabel(self.labelDimentionsGroup)
        self.yLabel.setObjectName("yLabel")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.yLabel)
        self.value_Y = QtWidgets.QSpinBox(self.labelDimentionsGroup)
        self.value_Y.setObjectName("value_Y")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.value_Y)
        self.gridLayout.addWidget(self.labelDimentionsGroup, 0, 0, 1, 1)
        self.labelIncludeGroup = QtWidgets.QGroupBox(self.labelPrefPage)
        self.labelIncludeGroup.setObjectName("labelIncludeGroup")
        self.formLayout_3 = QtWidgets.QFormLayout(self.labelIncludeGroup)
        self.formLayout_3.setObjectName("formLayout_3")
        self.value_inc_Associated = QtWidgets.QCheckBox(self.labelIncludeGroup)
        self.value_inc_Associated.setChecked(True)
        self.value_inc_Associated.setObjectName("value_inc_Associated")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.value_inc_Associated)
        self.value_inc_VerifiedBy = QtWidgets.QCheckBox(self.labelIncludeGroup)
        self.value_inc_VerifiedBy.setObjectName("value_inc_VerifiedBy")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.value_inc_VerifiedBy)
        self.value_VerifiedBy = QtWidgets.QLineEdit(self.labelIncludeGroup)
        self.value_VerifiedBy.setObjectName("value_VerifiedBy")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.value_VerifiedBy)
        self.value_inc_CollectionName = QtWidgets.QCheckBox(self.labelIncludeGroup)
        self.value_inc_CollectionName.setObjectName("value_inc_CollectionName")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.value_inc_CollectionName)
        self.value_CollectionName = QtWidgets.QPlainTextEdit(self.labelIncludeGroup)
        self.value_CollectionName.setEnabled(False)
        self.value_CollectionName.setObjectName("value_CollectionName")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.value_CollectionName)
        self.value_inc_Barcode = QtWidgets.QCheckBox(self.labelIncludeGroup)
        self.value_inc_Barcode.setEnabled(False)
        self.value_inc_Barcode.setObjectName("value_inc_Barcode")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.value_inc_Barcode)
        self.gridLayout.addWidget(self.labelIncludeGroup, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.labelPrefPage)
        self.TaxPrefPage = QtWidgets.QWidget()
        self.TaxPrefPage.setObjectName("TaxPrefPage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.TaxPrefPage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.TaxPrefPage)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_5 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_TaxAlignSource = QtWidgets.QLabel(self.groupBox)
        self.label_TaxAlignSource.setObjectName("label_TaxAlignSource")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_TaxAlignSource)
        self.value_TaxAlignSource = QtWidgets.QComboBox(self.groupBox)
        self.value_TaxAlignSource.setObjectName("value_TaxAlignSource")
        self.value_TaxAlignSource.addItem("")
        self.value_TaxAlignSource.addItem("")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.value_TaxAlignSource)
        self.label_NameChangePolicy = QtWidgets.QLabel(self.groupBox)
        self.label_NameChangePolicy.setObjectName("label_NameChangePolicy")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_NameChangePolicy)
        self.value_NameChangePolicy = QtWidgets.QComboBox(self.groupBox)
        self.value_NameChangePolicy.setObjectName("value_NameChangePolicy")
        self.value_NameChangePolicy.addItem("")
        self.value_NameChangePolicy.addItem("")
        self.value_NameChangePolicy.addItem("")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.value_NameChangePolicy)
        self.label_AuthChangePolicy = QtWidgets.QLabel(self.groupBox)
        self.label_AuthChangePolicy.setObjectName("label_AuthChangePolicy")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_AuthChangePolicy)
        self.value_AuthChangePolicy = QtWidgets.QComboBox(self.groupBox)
        self.value_AuthChangePolicy.setObjectName("value_AuthChangePolicy")
        self.value_AuthChangePolicy.addItem("")
        self.value_AuthChangePolicy.addItem("")
        self.value_AuthChangePolicy.addItem("")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.value_AuthChangePolicy)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.TaxPrefPage)
        self.upperHorizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout.addLayout(self.upperHorizontalLayout)
        self.lowerHorizontalLayout = QtWidgets.QHBoxLayout()
        self.lowerHorizontalLayout.setObjectName("lowerHorizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lowerHorizontalLayout.addItem(spacerItem)
        self.button_Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.button_Cancel.setObjectName("button_Cancel")
        self.lowerHorizontalLayout.addWidget(self.button_Cancel)
        self.button_SaveExit = QtWidgets.QPushButton(self.centralwidget)
        self.button_SaveExit.setAutoDefault(False)
        self.button_SaveExit.setObjectName("button_SaveExit")
        self.lowerHorizontalLayout.addWidget(self.button_SaveExit)
        self.verticalLayout.addLayout(self.lowerHorizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        settingsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(settingsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 539, 22))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        settingsWindow.setMenuBar(self.menubar)

        self.retranslateUi(settingsWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.selectionWidget.currentRowChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        self.value_inc_VerifiedBy.toggled['bool'].connect(self.value_VerifiedBy.setEnabled)
        self.value_inc_VerifiedBy.stateChanged['int'].connect(self.value_VerifiedBy.setFocus)
        self.value_inc_CollectionName.toggled['bool'].connect(self.value_CollectionName.setEnabled)
        self.value_inc_CollectionName.stateChanged['int'].connect(self.value_CollectionName.setFocus)
        QtCore.QMetaObject.connectSlotsByName(settingsWindow)

    def retranslateUi(self, settingsWindow):
        _translate = QtCore.QCoreApplication.translate
        settingsWindow.setWindowTitle(_translate("settingsWindow", "Preferences"))
        __sortingEnabled = self.selectionWidget.isSortingEnabled()
        self.selectionWidget.setSortingEnabled(False)
        item = self.selectionWidget.item(0)
        item.setText(_translate("settingsWindow", "Label preferences"))
        item = self.selectionWidget.item(1)
        item.setText(_translate("settingsWindow", "Taxanomic preferences"))
        self.selectionWidget.setSortingEnabled(__sortingEnabled)
        self.labelDimentionsGroup.setTitle(_translate("settingsWindow", "Label dimensions (mm)"))
        self.xLabel.setText(_translate("settingsWindow", "width (mm)"))
        self.yLabel.setText(_translate("settingsWindow", "height (mm)"))
        self.labelIncludeGroup.setTitle(_translate("settingsWindow", "Include"))
        self.value_inc_Associated.setText(_translate("settingsWindow", "Include associated taxa"))
        self.value_inc_VerifiedBy.setText(_translate("settingsWindow", "Include verified by"))
        self.value_inc_CollectionName.setText(_translate("settingsWindow", "Include collection name"))
        self.value_inc_Barcode.setText(_translate("settingsWindow", "Include catalogNumber barcode"))
        self.groupBox.setTitle(_translate("settingsWindow", "Taxanomic alignment"))
        self.label_TaxAlignSource.setText(_translate("settingsWindow", "Source"))
        self.value_TaxAlignSource.setItemText(0, _translate("settingsWindow", "ITIS (local)"))
        self.value_TaxAlignSource.setItemText(1, _translate("settingsWindow", "Catalog of Life (web api)"))
        self.label_NameChangePolicy.setText(_translate("settingsWindow", "Name change policy"))
        self.value_NameChangePolicy.setItemText(0, _translate("settingsWindow", "Always ask"))
        self.value_NameChangePolicy.setItemText(1, _translate("settingsWindow", "Accept all suggestions"))
        self.value_NameChangePolicy.setItemText(2, _translate("settingsWindow", "Fill all blanks"))
        self.label_AuthChangePolicy.setText(_translate("settingsWindow", "Authority change policy"))
        self.value_AuthChangePolicy.setItemText(0, _translate("settingsWindow", "Fill in blanks"))
        self.value_AuthChangePolicy.setItemText(1, _translate("settingsWindow", "Accept all suggestions"))
        self.value_AuthChangePolicy.setItemText(2, _translate("settingsWindow", "Always ask"))
        self.button_Cancel.setText(_translate("settingsWindow", "Cancel"))
        self.button_SaveExit.setText(_translate("settingsWindow", "Save and exit"))

import Resources_rc
