# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/TestUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1007, 697)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tree_widget = QtWidgets.QTreeWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_widget.sizePolicy().hasHeightForWidth())
        self.tree_widget.setSizePolicy(sizePolicy)
        self.tree_widget.setMinimumSize(QtCore.QSize(150, 0))
        self.tree_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tree_widget.setSizeIncrement(QtCore.QSize(0, 0))
        self.tree_widget.setBaseSize(QtCore.QSize(150, 0))
        self.tree_widget.setMouseTracking(False)
        self.tree_widget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tree_widget.setFrameShape(QtWidgets.QFrame.Panel)
        self.tree_widget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tree_widget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tree_widget.setProperty("showDropIndicator", False)
        self.tree_widget.setAlternatingRowColors(True)
        self.tree_widget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tree_widget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tree_widget.setExpandsOnDoubleClick(True)
        self.tree_widget.setObjectName("tree_widget")
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_widget)
        self.horizontalLayout.addWidget(self.tree_widget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formView = formView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formView.sizePolicy().hasHeightForWidth())
        self.formView.setSizePolicy(sizePolicy)
        self.formView.setMinimumSize(QtCore.QSize(0, 0))
        self.formView.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.formView.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.formView.setTabPosition(QtWidgets.QTabWidget.North)
        self.formView.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.formView.setUsesScrollButtons(False)
        self.formView.setDocumentMode(True)
        self.formView.setTabBarAutoHide(False)
        self.formView.setObjectName("formView")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setContentsMargins(0, 9, 0, 3)
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_13.addWidget(self.pushButton_5)
        self.gridLayout.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.formView.addTab(self.tab, "")
        self.SiteData = QtWidgets.QWidget()
        self.SiteData.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.SiteData.setObjectName("SiteData")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.SiteData)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_4 = QtWidgets.QPushButton(self.SiteData)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_12.addWidget(self.pushButton_4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.checkBox_2 = QtWidgets.QCheckBox(self.SiteData)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_12.addWidget(self.checkBox_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.SiteData)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_12.addWidget(self.pushButton_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.scrollArea = QtWidgets.QScrollArea(self.SiteData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 560, 353))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(-1, 3, -1, 3)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupGrid_event = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupGrid_event.sizePolicy().hasHeightForWidth())
        self.groupGrid_event.setSizePolicy(sizePolicy)
        self.groupGrid_event.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupGrid_event.setCheckable(False)
        self.groupGrid_event.setObjectName("groupGrid_event")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupGrid_event)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setContentsMargins(-1, 3, -1, 3)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_associatedCollectors = QtWidgets.QLabel(self.groupGrid_event)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_associatedCollectors.sizePolicy().hasHeightForWidth())
        self.label_associatedCollectors.setSizePolicy(sizePolicy)
        self.label_associatedCollectors.setWordWrap(False)
        self.label_associatedCollectors.setObjectName("label_associatedCollectors")
        self.gridLayout_4.addWidget(self.label_associatedCollectors, 0, 2, 1, 1)
        self.label_eventDate = QtWidgets.QLabel(self.groupGrid_event)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_eventDate.sizePolicy().hasHeightForWidth())
        self.label_eventDate.setSizePolicy(sizePolicy)
        self.label_eventDate.setWordWrap(False)
        self.label_eventDate.setObjectName("label_eventDate")
        self.gridLayout_4.addWidget(self.label_eventDate, 0, 0, 1, 1)
        self.lineEdit_recordedBy = QtWidgets.QLineEdit(self.groupGrid_event)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_recordedBy.sizePolicy().hasHeightForWidth())
        self.lineEdit_recordedBy.setSizePolicy(sizePolicy)
        self.lineEdit_recordedBy.setObjectName("lineEdit_recordedBy")
        self.gridLayout_4.addWidget(self.lineEdit_recordedBy, 1, 1, 1, 1)
        self.label_recordedBy = QtWidgets.QLabel(self.groupGrid_event)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_recordedBy.sizePolicy().hasHeightForWidth())
        self.label_recordedBy.setSizePolicy(sizePolicy)
        self.label_recordedBy.setObjectName("label_recordedBy")
        self.gridLayout_4.addWidget(self.label_recordedBy, 0, 1, 1, 1)
        self.lineEdit_associatedCollectors = QtWidgets.QLineEdit(self.groupGrid_event)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_associatedCollectors.sizePolicy().hasHeightForWidth())
        self.lineEdit_associatedCollectors.setSizePolicy(sizePolicy)
        self.lineEdit_associatedCollectors.setObjectName("lineEdit_associatedCollectors")
        self.gridLayout_4.addWidget(self.lineEdit_associatedCollectors, 1, 2, 1, 1)
        self.dateEdit_eventDate = QtWidgets.QDateEdit(self.groupGrid_event)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_eventDate.sizePolicy().hasHeightForWidth())
        self.dateEdit_eventDate.setSizePolicy(sizePolicy)
        self.dateEdit_eventDate.setWrapping(False)
        self.dateEdit_eventDate.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_eventDate.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit_eventDate.setAccelerated(False)
        self.dateEdit_eventDate.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEdit_eventDate.setCalendarPopup(True)
        self.dateEdit_eventDate.setCurrentSectionIndex(2)
        self.dateEdit_eventDate.setObjectName("dateEdit_eventDate")
        self.gridLayout_4.addWidget(self.dateEdit_eventDate, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupGrid_event)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setContentsMargins(9, 3, 9, 3)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_county = QtWidgets.QLabel(self.groupBox)
        self.label_county.setObjectName("label_county")
        self.gridLayout_3.addWidget(self.label_county, 5, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_associatedTaxa = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_associatedTaxa.sizePolicy().hasHeightForWidth())
        self.label_associatedTaxa.setSizePolicy(sizePolicy)
        self.label_associatedTaxa.setObjectName("label_associatedTaxa")
        self.horizontalLayout_7.addWidget(self.label_associatedTaxa)
        self.button_associatedTaxa = QtWidgets.QToolButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_associatedTaxa.sizePolicy().hasHeightForWidth())
        self.button_associatedTaxa.setSizePolicy(sizePolicy)
        self.button_associatedTaxa.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.button_associatedTaxa.setSizeIncrement(QtCore.QSize(0, 0))
        self.button_associatedTaxa.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rc_/plus-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_associatedTaxa.setIcon(icon)
        self.button_associatedTaxa.setObjectName("button_associatedTaxa")
        self.horizontalLayout_7.addWidget(self.button_associatedTaxa, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.lineEdit_associatedTaxa = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_associatedTaxa.setObjectName("lineEdit_associatedTaxa")
        self.horizontalLayout_7.addWidget(self.lineEdit_associatedTaxa)
        self.horizontalLayout_7.setStretch(2, 10)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 0, 0, 1, 2)
        self.lineEdit_path = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.gridLayout_3.addWidget(self.lineEdit_path, 10, 1, 1, 1)
        self.lineEdit_stateProvince = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_stateProvince.setObjectName("lineEdit_stateProvince")
        self.gridLayout_3.addWidget(self.lineEdit_stateProvince, 6, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_habitat = QtWidgets.QLabel(self.groupBox)
        self.label_habitat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_habitat.setObjectName("label_habitat")
        self.horizontalLayout_8.addWidget(self.label_habitat)
        self.lineEdit_habitat = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_habitat.setObjectName("lineEdit_habitat")
        self.horizontalLayout_8.addWidget(self.lineEdit_habitat)
        self.label_locationNotes = QtWidgets.QLabel(self.groupBox)
        self.label_locationNotes.setObjectName("label_locationNotes")
        self.horizontalLayout_8.addWidget(self.label_locationNotes)
        self.lineEdit_locationNotes = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_locationNotes.setObjectName("lineEdit_locationNotes")
        self.horizontalLayout_8.addWidget(self.lineEdit_locationNotes)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 1, 0, 1, 2)
        self.label_municipality = QtWidgets.QLabel(self.groupBox)
        self.label_municipality.setObjectName("label_municipality")
        self.gridLayout_3.addWidget(self.label_municipality, 9, 0, 1, 1)
        self.label_path = QtWidgets.QLabel(self.groupBox)
        self.label_path.setObjectName("label_path")
        self.gridLayout_3.addWidget(self.label_path, 9, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_decimalLongitude = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_decimalLongitude.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lineEdit_decimalLongitude.setObjectName("lineEdit_decimalLongitude")
        self.gridLayout_2.addWidget(self.lineEdit_decimalLongitude, 1, 1, 1, 1)
        self.label_latitude = QtWidgets.QLabel(self.groupBox)
        self.label_latitude.setObjectName("label_latitude")
        self.gridLayout_2.addWidget(self.label_latitude, 0, 0, 1, 1)
        self.lineEdit_coordinateUncertaintyInMeters = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_coordinateUncertaintyInMeters.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lineEdit_coordinateUncertaintyInMeters.setObjectName("lineEdit_coordinateUncertaintyInMeters")
        self.gridLayout_2.addWidget(self.lineEdit_coordinateUncertaintyInMeters, 1, 2, 1, 1)
        self.label_uncertainty = QtWidgets.QLabel(self.groupBox)
        self.label_uncertainty.setObjectName("label_uncertainty")
        self.gridLayout_2.addWidget(self.label_uncertainty, 0, 2, 1, 1)
        self.lineEdit_decimalLatitude = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_decimalLatitude.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lineEdit_decimalLatitude.setObjectName("lineEdit_decimalLatitude")
        self.gridLayout_2.addWidget(self.lineEdit_decimalLatitude, 1, 0, 1, 1)
        self.label_longitude = QtWidgets.QLabel(self.groupBox)
        self.label_longitude.setObjectName("label_longitude")
        self.gridLayout_2.addWidget(self.label_longitude, 0, 1, 1, 1)
        self.label_elevation = QtWidgets.QLabel(self.groupBox)
        self.label_elevation.setObjectName("label_elevation")
        self.gridLayout_2.addWidget(self.label_elevation, 0, 3, 1, 1)
        self.lineEdit_minimumElevationInMeters = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_minimumElevationInMeters.setObjectName("lineEdit_minimumElevationInMeters")
        self.gridLayout_2.addWidget(self.lineEdit_minimumElevationInMeters, 1, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 3, 0, 1, 2)
        self.label_stateProvince = QtWidgets.QLabel(self.groupBox)
        self.label_stateProvince.setObjectName("label_stateProvince")
        self.gridLayout_3.addWidget(self.label_stateProvince, 5, 0, 1, 1)
        self.lineEdit_county = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_county.setObjectName("lineEdit_county")
        self.gridLayout_3.addWidget(self.lineEdit_county, 6, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_locality = QtWidgets.QLabel(self.groupBox)
        self.label_locality.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_locality.setObjectName("label_locality")
        self.horizontalLayout_6.addWidget(self.label_locality)
        self.plainTextEdit_locality = QtWidgets.QPlainTextEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_locality.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_locality.setSizePolicy(sizePolicy)
        self.plainTextEdit_locality.setMinimumSize(QtCore.QSize(0, 45))
        self.plainTextEdit_locality.setMaximumSize(QtCore.QSize(16777215, 50))
        self.plainTextEdit_locality.setBackgroundVisible(False)
        self.plainTextEdit_locality.setObjectName("plainTextEdit_locality")
        self.horizontalLayout_6.addWidget(self.plainTextEdit_locality)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 2, 0, 1, 2)
        self.lineEdit_municipality = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_municipality.setObjectName("lineEdit_municipality")
        self.gridLayout_3.addWidget(self.lineEdit_municipality, 10, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox, 0, QtCore.Qt.AlignTop)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.formView.addTab(self.SiteData, "")
        self.SpecimenData = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpecimenData.sizePolicy().hasHeightForWidth())
        self.SpecimenData.setSizePolicy(sizePolicy)
        self.SpecimenData.setObjectName("SpecimenData")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.SpecimenData)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_3 = QtWidgets.QPushButton(self.SpecimenData)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_10.addWidget(self.pushButton_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.checkBox = QtWidgets.QCheckBox(self.SpecimenData)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_10.addWidget(self.checkBox)
        self.pushButton = QtWidgets.QPushButton(self.SpecimenData)
        self.pushButton.setEnabled(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_10.addWidget(self.pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setVerticalSpacing(3)
        self.formLayout.setObjectName("formLayout")
        self.label_sciName = QtWidgets.QLabel(self.SpecimenData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sciName.sizePolicy().hasHeightForWidth())
        self.label_sciName.setSizePolicy(sizePolicy)
        self.label_sciName.setObjectName("label_sciName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_sciName)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_sciName = QtWidgets.QLineEdit(self.SpecimenData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_sciName.sizePolicy().hasHeightForWidth())
        self.lineEdit_sciName.setSizePolicy(sizePolicy)
        self.lineEdit_sciName.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_sciName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_sciName.setObjectName("lineEdit_sciName")
        self.horizontalLayout_2.addWidget(self.lineEdit_sciName)
        self.label_sciNameAuthority = QtWidgets.QLabel(self.SpecimenData)
        self.label_sciNameAuthority.setObjectName("label_sciNameAuthority")
        self.horizontalLayout_2.addWidget(self.label_sciNameAuthority)
        self.lineEdit_sciNameAuthority = QtWidgets.QLineEdit(self.SpecimenData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_sciNameAuthority.sizePolicy().hasHeightForWidth())
        self.lineEdit_sciNameAuthority.setSizePolicy(sizePolicy)
        self.lineEdit_sciNameAuthority.setObjectName("lineEdit_sciNameAuthority")
        self.horizontalLayout_2.addWidget(self.lineEdit_sciNameAuthority)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 2)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.occurrenceRemarksLabel = QtWidgets.QLabel(self.SpecimenData)
        self.occurrenceRemarksLabel.setObjectName("occurrenceRemarksLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.occurrenceRemarksLabel)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_occurrenceRemarks = QtWidgets.QLineEdit(self.SpecimenData)
        self.lineEdit_occurrenceRemarks.setObjectName("lineEdit_occurrenceRemarks")
        self.horizontalLayout_4.addWidget(self.lineEdit_occurrenceRemarks)
        self.label_substrate = QtWidgets.QLabel(self.SpecimenData)
        self.label_substrate.setObjectName("label_substrate")
        self.horizontalLayout_4.addWidget(self.label_substrate)
        self.lineEdit_substrate = QtWidgets.QLineEdit(self.SpecimenData)
        self.lineEdit_substrate.setObjectName("lineEdit_substrate")
        self.horizontalLayout_4.addWidget(self.lineEdit_substrate)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_reproductiveCondition = QtWidgets.QLabel(self.SpecimenData)
        self.label_reproductiveCondition.setObjectName("label_reproductiveCondition")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_reproductiveCondition)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.comboBox_reproductiveCondition = QtWidgets.QComboBox(self.SpecimenData)
        self.comboBox_reproductiveCondition.setObjectName("comboBox_reproductiveCondition")
        self.comboBox_reproductiveCondition.addItem("")
        self.comboBox_reproductiveCondition.setItemText(0, "")
        self.comboBox_reproductiveCondition.addItem("")
        self.comboBox_reproductiveCondition.addItem("")
        self.comboBox_reproductiveCondition.addItem("")
        self.comboBox_reproductiveCondition.addItem("")
        self.comboBox_reproductiveCondition.addItem("")
        self.comboBox_reproductiveCondition.addItem("")
        self.comboBox_reproductiveCondition.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_reproductiveCondition)
        self.label_individualCount = QtWidgets.QLabel(self.SpecimenData)
        self.label_individualCount.setObjectName("label_individualCount")
        self.horizontalLayout_5.addWidget(self.label_individualCount, 0, QtCore.Qt.AlignRight)
        self.spinBox_individualCount = QtWidgets.QSpinBox(self.SpecimenData)
        self.spinBox_individualCount.setMaximum(99999)
        self.spinBox_individualCount.setProperty("value", 0)
        self.spinBox_individualCount.setObjectName("spinBox_individualCount")
        self.horizontalLayout_5.addWidget(self.spinBox_individualCount)
        self.checkBox_establishmentMeans = QtWidgets.QCheckBox(self.SpecimenData)
        self.checkBox_establishmentMeans.setObjectName("checkBox_establishmentMeans")
        self.horizontalLayout_5.addWidget(self.checkBox_establishmentMeans)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(3, 1)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_identificationRemarks = QtWidgets.QLabel(self.SpecimenData)
        self.label_identificationRemarks.setObjectName("label_identificationRemarks")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_identificationRemarks)
        self.plainTextEdit_identificationRemarks = QtWidgets.QPlainTextEdit(self.SpecimenData)
        self.plainTextEdit_identificationRemarks.setMinimumSize(QtCore.QSize(0, 45))
        self.plainTextEdit_identificationRemarks.setMaximumSize(QtCore.QSize(16777215, 50))
        self.plainTextEdit_identificationRemarks.setObjectName("plainTextEdit_identificationRemarks")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit_identificationRemarks)
        self.plainTextEdit_identificationReferences = QtWidgets.QPlainTextEdit(self.SpecimenData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_identificationReferences.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_identificationReferences.setSizePolicy(sizePolicy)
        self.plainTextEdit_identificationReferences.setMinimumSize(QtCore.QSize(0, 45))
        self.plainTextEdit_identificationReferences.setMaximumSize(QtCore.QSize(16777215, 50))
        self.plainTextEdit_identificationReferences.setObjectName("plainTextEdit_identificationReferences")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit_identificationReferences)
        self.label_identificationReferences = QtWidgets.QLabel(self.SpecimenData)
        self.label_identificationReferences.setObjectName("label_identificationReferences")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_identificationReferences)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit_otherCatalogNumbers = QtWidgets.QLineEdit(self.SpecimenData)
        self.lineEdit_otherCatalogNumbers.setEnabled(False)
        self.lineEdit_otherCatalogNumbers.setObjectName("lineEdit_otherCatalogNumbers")
        self.horizontalLayout_9.addWidget(self.lineEdit_otherCatalogNumbers)
        self.label_catalogNumber = QtWidgets.QLabel(self.SpecimenData)
        self.label_catalogNumber.setObjectName("label_catalogNumber")
        self.horizontalLayout_9.addWidget(self.label_catalogNumber)
        self.lineEdit_catalogNumber = QtWidgets.QLineEdit(self.SpecimenData)
        self.lineEdit_catalogNumber.setObjectName("lineEdit_catalogNumber")
        self.horizontalLayout_9.addWidget(self.lineEdit_catalogNumber)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.label_otherCatalogNumber = QtWidgets.QLabel(self.SpecimenData)
        self.label_otherCatalogNumber.setObjectName("label_otherCatalogNumber")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_otherCatalogNumber)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.formView.addTab(self.SpecimenData, "")
        self.horizontalLayout_3.addWidget(self.formView, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lower_horizontalLayout = QtWidgets.QHBoxLayout()
        self.lower_horizontalLayout.setObjectName("lower_horizontalLayout")
        self.pdf_preview = PDFViewer(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pdf_preview.sizePolicy().hasHeightForWidth())
        self.pdf_preview.setSizePolicy(sizePolicy)
        self.pdf_preview.setMinimumSize(QtCore.QSize(0, 0))
        self.pdf_preview.setText("")
        self.pdf_preview.setObjectName("pdf_preview")
        self.lower_horizontalLayout.addWidget(self.pdf_preview)
        self.table_view = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_view.sizePolicy().hasHeightForWidth())
        self.table_view.setSizePolicy(sizePolicy)
        self.table_view.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.table_view.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.table_view.setAlternatingRowColors(False)
        self.table_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_view.setIconSize(QtCore.QSize(100, 100))
        self.table_view.setGridStyle(QtCore.Qt.DashLine)
        self.table_view.setSortingEnabled(True)
        self.table_view.setObjectName("table_view")
        self.table_view.verticalHeader().setCascadingSectionResizes(False)
        self.table_view.verticalHeader().setSortIndicatorShown(False)
        self.lower_horizontalLayout.addWidget(self.table_view)
        self.verticalLayout.addLayout(self.lower_horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1007, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.left_toolBar = QtWidgets.QToolBar(MainWindow)
        self.left_toolBar.setObjectName("left_toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.left_toolBar)
        self.right_toolBar = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_toolBar.sizePolicy().hasHeightForWidth())
        self.right_toolBar.setSizePolicy(sizePolicy)
        self.right_toolBar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.right_toolBar.setObjectName("right_toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.right_toolBar)
        self.action_Open = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/rc_/file-text.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Open.setIcon(icon1)
        self.action_Open.setObjectName("action_Open")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/rc_/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Exit.setIcon(icon2)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Verify_Taxonomy = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/rc_/check-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Verify_Taxonomy.setIcon(icon3)
        self.action_Verify_Taxonomy.setObjectName("action_Verify_Taxonomy")
        self.action_Reverse_Geolocate = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/rc_/map-pin.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_Reverse_Geolocate.setIcon(icon4)
        self.action_Reverse_Geolocate.setObjectName("action_Reverse_Geolocate")
        self.action_Save_As = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/rc_/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Save_As.setIcon(icon5)
        self.action_Save_As.setObjectName("action_Save_As")
        self.action_New_Records = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/rc_/file-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_New_Records.setIcon(icon6)
        self.action_New_Records.setObjectName("action_New_Records")
        self.action_undo = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/rc_/corner-down-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/icons/corner-down-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_undo.setIcon(icon7)
        self.action_undo.setObjectName("action_undo")
        self.action_Redo = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/rc_/corner-down-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/icons/corner-down-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_Redo.setIcon(icon8)
        self.action_Redo.setObjectName("action_Redo")
        self.action_Settings = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/rc_/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Settings.setIcon(icon9)
        self.action_Settings.setObjectName("action_Settings")
        self.action_Export_Labels = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/rc_/tag.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Export_Labels.setIcon(icon10)
        self.action_Export_Labels.setObjectName("action_Export_Labels")
        self.actionTestFunction = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/rc_/circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTestFunction.setIcon(icon11)
        self.actionTestFunction.setObjectName("actionTestFunction")
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.action_New_Records)
        self.menu_File.addAction(self.action_Save_As)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Exit)
        self.menubar.addAction(self.menu_File.menuAction())
        self.left_toolBar.addAction(self.action_New_Records)
        self.left_toolBar.addAction(self.action_Open)
        self.left_toolBar.addAction(self.action_Save_As)
        self.left_toolBar.addSeparator()
        self.left_toolBar.addAction(self.action_undo)
        self.left_toolBar.addAction(self.action_Redo)
        self.left_toolBar.addSeparator()
        self.left_toolBar.addAction(self.action_Verify_Taxonomy)
        self.left_toolBar.addAction(self.action_Reverse_Geolocate)
        self.left_toolBar.addAction(self.action_Settings)
        self.left_toolBar.addAction(self.action_Export_Labels)
        self.right_toolBar.addSeparator()
        self.right_toolBar.addAction(self.action_Exit)
        self.right_toolBar.addAction(self.actionTestFunction)

        self.retranslateUi(MainWindow)
        self.formView.setCurrentIndex(2)
        self.tree_widget.currentItemChanged['QTreeWidgetItem*','QTreeWidgetItem*'].connect(MainWindow.updateTableView)
        self.checkBox.toggled['bool'].connect(self.pushButton.setEnabled)
        self.checkBox_2.toggled['bool'].connect(self.pushButton_2.setEnabled)
        self.formView.tabBarClicked['int'].connect(MainWindow.selectTreeWidgetItemByIndex)
        self.table_view.clicked['QModelIndex'].connect(MainWindow.updatePreview)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tree_widget, self.lineEdit_sciName)
        MainWindow.setTabOrder(self.lineEdit_sciName, self.lineEdit_stateProvince)
        MainWindow.setTabOrder(self.lineEdit_stateProvince, self.lineEdit_county)
        MainWindow.setTabOrder(self.lineEdit_county, self.lineEdit_municipality)
        MainWindow.setTabOrder(self.lineEdit_municipality, self.lineEdit_path)
        MainWindow.setTabOrder(self.lineEdit_path, self.scrollArea)
        MainWindow.setTabOrder(self.scrollArea, self.lineEdit_sciNameAuthority)
        MainWindow.setTabOrder(self.lineEdit_sciNameAuthority, self.table_view)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tree_widget.headerItem().setText(0, _translate("MainWindow", "Sites"))
        __sortingEnabled = self.tree_widget.isSortingEnabled()
        self.tree_widget.setSortingEnabled(False)
        self.tree_widget.topLevelItem(0).setText(0, _translate("MainWindow", "All Records"))
        self.tree_widget.setSortingEnabled(__sortingEnabled)
        self.pushButton_5.setText(_translate("MainWindow", "Add new site"))
        self.formView.setTabText(self.formView.indexOf(self.tab), _translate("MainWindow", "All Records"))
        self.pushButton_4.setText(_translate("MainWindow", "Add specimen"))
        self.pushButton_2.setText(_translate("MainWindow", "Delete site"))
        self.groupGrid_event.setTitle(_translate("MainWindow", "Event"))
        self.label_associatedCollectors.setText(_translate("MainWindow", "Associated Collectors (comma seperated)"))
        self.label_eventDate.setText(_translate("MainWindow", "Date (of collection)"))
        self.label_recordedBy.setText(_translate("MainWindow", "Primary Collector"))
        self.dateEdit_eventDate.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.groupBox.setTitle(_translate("MainWindow", "Location"))
        self.label_county.setText(_translate("MainWindow", "County"))
        self.label_associatedTaxa.setText(_translate("MainWindow", "Associated Taxa"))
        self.label_habitat.setText(_translate("MainWindow", "Habitat"))
        self.label_locationNotes.setText(_translate("MainWindow", "Location Notes"))
        self.label_municipality.setText(_translate("MainWindow", "Municipality"))
        self.label_path.setText(_translate("MainWindow", "Path (road or trail name)"))
        self.lineEdit_decimalLongitude.setInputMask(_translate("MainWindow", "#099.9900000000"))
        self.label_latitude.setText(_translate("MainWindow", "Latitude (decimal deg)"))
        self.lineEdit_coordinateUncertaintyInMeters.setInputMask(_translate("MainWindow", "00009.000"))
        self.label_uncertainty.setText(_translate("MainWindow", "Uncertainty (m)"))
        self.lineEdit_decimalLatitude.setInputMask(_translate("MainWindow", "#099.9900000000"))
        self.label_longitude.setText(_translate("MainWindow", "Longitude (decimal deg)"))
        self.label_elevation.setText(_translate("MainWindow", "Elevation (m)"))
        self.lineEdit_minimumElevationInMeters.setInputMask(_translate("MainWindow", "0009.00"))
        self.lineEdit_minimumElevationInMeters.setText(_translate("MainWindow", "."))
        self.label_stateProvince.setText(_translate("MainWindow", " State/Province"))
        self.label_locality.setText(_translate("MainWindow", "Locality"))
        self.formView.setTabText(self.formView.indexOf(self.SiteData), _translate("MainWindow", "Site Data"))
        self.pushButton_3.setText(_translate("MainWindow", "Duplicate record"))
        self.pushButton.setText(_translate("MainWindow", "Delete record"))
        self.label_sciName.setText(_translate("MainWindow", "Scientific Name"))
        self.label_sciNameAuthority.setText(_translate("MainWindow", "Authority"))
        self.occurrenceRemarksLabel.setText(_translate("MainWindow", "Occurrence Remarks"))
        self.label_substrate.setText(_translate("MainWindow", "Substrate"))
        self.label_reproductiveCondition.setText(_translate("MainWindow", "Reproductive Condition"))
        self.comboBox_reproductiveCondition.setItemText(1, _translate("MainWindow", "Vegetative"))
        self.comboBox_reproductiveCondition.setItemText(2, _translate("MainWindow", "Reproductive"))
        self.comboBox_reproductiveCondition.setItemText(3, _translate("MainWindow", "    Early reproductive"))
        self.comboBox_reproductiveCondition.setItemText(4, _translate("MainWindow", "    Peak reproductive"))
        self.comboBox_reproductiveCondition.setItemText(5, _translate("MainWindow", "    Late reproductive"))
        self.comboBox_reproductiveCondition.setItemText(6, _translate("MainWindow", "    Fruit / seed bearing"))
        self.comboBox_reproductiveCondition.setItemText(7, _translate("MainWindow", "N/A"))
        self.label_individualCount.setText(_translate("MainWindow", "Est. Qty"))
        self.checkBox_establishmentMeans.setText(_translate("MainWindow", "Cultivated"))
        self.label_identificationRemarks.setText(_translate("MainWindow", "Identification Remarks"))
        self.label_identificationReferences.setText(_translate("MainWindow", "Identification References "))
        self.label_catalogNumber.setText(_translate("MainWindow", "Catalog Number"))
        self.label_otherCatalogNumber.setText(_translate("MainWindow", "Field Number"))
        self.formView.setTabText(self.formView.indexOf(self.SpecimenData), _translate("MainWindow", "Specimen Data"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.left_toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.right_toolBar.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.action_Open.setText(_translate("MainWindow", "&Open"))
        self.action_Open.setToolTip(_translate("MainWindow", "Open a CSV file"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))
        self.action_Verify_Taxonomy.setText(_translate("MainWindow", "&Verify Taxonomy"))
        self.action_Verify_Taxonomy.setToolTip(_translate("MainWindow", "align scientific names & retrieve authorities"))
        self.action_Reverse_Geolocate.setText(_translate("MainWindow", "&Reverse Geolocate"))
        self.action_Reverse_Geolocate.setToolTip(_translate("MainWindow", "Use GPS coordinates to prepend locality details"))
        self.action_Save_As.setText(_translate("MainWindow", "&Save As"))
        self.action_Save_As.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_New_Records.setText(_translate("MainWindow", "&New Records"))
        self.action_New_Records.setToolTip(_translate("MainWindow", "Generate a new, empty record list"))
        self.action_undo.setText(_translate("MainWindow", "&undo"))
        self.action_undo.setToolTip(_translate("MainWindow", "undo last major action"))
        self.action_Redo.setText(_translate("MainWindow", "&Redo"))
        self.action_Redo.setToolTip(_translate("MainWindow", "undo last major action"))
        self.action_Settings.setText(_translate("MainWindow", "&Settings"))
        self.action_Settings.setToolTip(_translate("MainWindow", "Settings and preferences"))
        self.action_Export_Labels.setText(_translate("MainWindow", "&Export_Labels"))
        self.actionTestFunction.setText(_translate("MainWindow", "&TestFunction"))
        self.actionTestFunction.setToolTip(_translate("MainWindow", "Test a function"))

from ui.formview import formView
from ui.pdfviewer import PDFViewer
import Resources_rc
