# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/TestUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(858, 572)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.upper_horizontalLayout = QtWidgets.QHBoxLayout()
        self.upper_horizontalLayout.setObjectName("upper_horizontalLayout")
        self.pdf_preview = PDFViewer(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdf_preview.sizePolicy().hasHeightForWidth())
        self.pdf_preview.setSizePolicy(sizePolicy)
        self.pdf_preview.setMinimumSize(QtCore.QSize(30, 30))
        self.pdf_preview.setText("")
        self.pdf_preview.setObjectName("pdf_preview")
        self.upper_horizontalLayout.addWidget(self.pdf_preview)
        self.record_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.record_groupBox.sizePolicy().hasHeightForWidth())
        self.record_groupBox.setSizePolicy(sizePolicy)
        self.record_groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.record_groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.record_groupBox.setObjectName("record_groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.record_groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.record_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.record_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.upper_horizontalLayout.addWidget(self.record_groupBox)
        self.verticalLayout.addLayout(self.upper_horizontalLayout)
        self.lower_horizontalLayout = QtWidgets.QHBoxLayout()
        self.lower_horizontalLayout.setObjectName("lower_horizontalLayout")
        self.tree_widget = QtWidgets.QTreeWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_widget.sizePolicy().hasHeightForWidth())
        self.tree_widget.setSizePolicy(sizePolicy)
        self.tree_widget.setMinimumSize(QtCore.QSize(150, 0))
        self.tree_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tree_widget.setSizeIncrement(QtCore.QSize(0, 0))
        self.tree_widget.setBaseSize(QtCore.QSize(150, 0))
        self.tree_widget.setMouseTracking(False)
        self.tree_widget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tree_widget.setFrameShape(QtWidgets.QFrame.Panel)
        self.tree_widget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tree_widget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tree_widget.setAlternatingRowColors(True)
        self.tree_widget.setExpandsOnDoubleClick(True)
        self.tree_widget.setObjectName("tree_widget")
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_widget)
        self.lower_horizontalLayout.addWidget(self.tree_widget)
        self.table_view = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_view.sizePolicy().hasHeightForWidth())
        self.table_view.setSizePolicy(sizePolicy)
        self.table_view.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.table_view.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.table_view.setAlternatingRowColors(True)
        self.table_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_view.setIconSize(QtCore.QSize(100, 100))
        self.table_view.setSortingEnabled(True)
        self.table_view.setObjectName("table_view")
        self.table_view.verticalHeader().setCascadingSectionResizes(False)
        self.table_view.verticalHeader().setSortIndicatorShown(False)
        self.lower_horizontalLayout.addWidget(self.table_view)
        self.verticalLayout.addLayout(self.lower_horizontalLayout)
        self.verticalLayout.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 858, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.left_toolBar = QtWidgets.QToolBar(MainWindow)
        self.left_toolBar.setObjectName("left_toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.left_toolBar)
        self.right_toolBar = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_toolBar.sizePolicy().hasHeightForWidth())
        self.right_toolBar.setSizePolicy(sizePolicy)
        self.right_toolBar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.right_toolBar.setObjectName("right_toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.right_toolBar)
        self.action_Open = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rc_/file-text.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Open.setIcon(icon)
        self.action_Open.setObjectName("action_Open")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/rc_/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Exit.setIcon(icon1)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Verify_Taxonomy = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/rc_/check-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Verify_Taxonomy.setIcon(icon2)
        self.action_Verify_Taxonomy.setObjectName("action_Verify_Taxonomy")
        self.action_Reverse_Geolocate = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/rc_/map-pin.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_Reverse_Geolocate.setIcon(icon3)
        self.action_Reverse_Geolocate.setObjectName("action_Reverse_Geolocate")
        self.action_Save_As = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/rc_/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Save_As.setIcon(icon4)
        self.action_Save_As.setObjectName("action_Save_As")
        self.action_New_Records = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/rc_/file-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_New_Records.setIcon(icon5)
        self.action_New_Records.setObjectName("action_New_Records")
        self.action_undo = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/rc_/corner-down-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/icons/corner-down-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_undo.setIcon(icon6)
        self.action_undo.setObjectName("action_undo")
        self.action_Redo = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/rc_/corner-down-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/icons/corner-down-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_Redo.setIcon(icon7)
        self.action_Redo.setObjectName("action_Redo")
        self.action_Settings = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/rc_/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Settings.setIcon(icon8)
        self.action_Settings.setObjectName("action_Settings")
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.action_New_Records)
        self.menu_File.addAction(self.action_Save_As)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Exit)
        self.menubar.addAction(self.menu_File.menuAction())
        self.left_toolBar.addAction(self.action_New_Records)
        self.left_toolBar.addAction(self.action_Open)
        self.left_toolBar.addAction(self.action_Save_As)
        self.left_toolBar.addSeparator()
        self.left_toolBar.addAction(self.action_undo)
        self.left_toolBar.addAction(self.action_Redo)
        self.left_toolBar.addSeparator()
        self.left_toolBar.addAction(self.action_Verify_Taxonomy)
        self.left_toolBar.addAction(self.action_Reverse_Geolocate)
        self.left_toolBar.addAction(self.action_Settings)
        self.right_toolBar.addSeparator()
        self.right_toolBar.addAction(self.action_Exit)

        self.retranslateUi(MainWindow)
        self.table_view.clicked['QModelIndex'].connect(MainWindow.updatePreview)
        self.tree_widget.currentItemChanged['QTreeWidgetItem*','QTreeWidgetItem*'].connect(MainWindow.updateTableView)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.record_groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.label.setText(_translate("MainWindow", "scientificName"))
        self.tree_widget.headerItem().setText(0, _translate("MainWindow", "Sites"))
        __sortingEnabled = self.tree_widget.isSortingEnabled()
        self.tree_widget.setSortingEnabled(False)
        self.tree_widget.topLevelItem(0).setText(0, _translate("MainWindow", "All Records"))
        self.tree_widget.setSortingEnabled(__sortingEnabled)
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.left_toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.right_toolBar.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.action_Open.setText(_translate("MainWindow", "&Open"))
        self.action_Open.setToolTip(_translate("MainWindow", "Open a CSV file"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))
        self.action_Verify_Taxonomy.setText(_translate("MainWindow", "&Verify Taxonomy"))
        self.action_Verify_Taxonomy.setToolTip(_translate("MainWindow", "align scientific names & retrieve authorities"))
        self.action_Reverse_Geolocate.setText(_translate("MainWindow", "&Reverse Geolocate"))
        self.action_Reverse_Geolocate.setToolTip(_translate("MainWindow", "Use GPS coordinates to prepend locality details"))
        self.action_Save_As.setText(_translate("MainWindow", "&Save As"))
        self.action_Save_As.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_New_Records.setText(_translate("MainWindow", "&New Records"))
        self.action_New_Records.setToolTip(_translate("MainWindow", "Generate a new, empty record list"))
        self.action_undo.setText(_translate("MainWindow", "&undo"))
        self.action_undo.setToolTip(_translate("MainWindow", "undo last major action"))
        self.action_Redo.setText(_translate("MainWindow", "&Redo"))
        self.action_Redo.setToolTip(_translate("MainWindow", "undo last major action"))
        self.action_Settings.setText(_translate("MainWindow", "&Settings"))
        self.action_Settings.setToolTip(_translate("MainWindow", "Settings and preferences"))

from ui.pdfviewer import PDFViewer
import Resources_rc
